import {Store} from './state.js';
import {StorageService} from './storage.js';
import {ParcelMap} from './map.js';
import {SyncService} from './sync.js';
import {applyImport, exportCsv, exportGeoJson, importPreviewHtml, inspectFiles, makeBackup, validateBackup} from './import-export.js?v=6';
import {campaignFor, download, escapeHtml, formatEuro, formatNumber, isoDate, localDate, localDateTime, normalize, toNumber, uid} from './utils.js';

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
let store, parcelMap, sync, currentView='dashboard', selectedParcelId=null, selectedDetailTab='summary', importPreview=null, weatherCache=null, fieldModeOpen=false;
$('#network-status').textContent='● Initialisation…';

async function init(){
  store=new Store(new StorageService()); await store.init(); sync=new SyncService(store); await sync.init();
  parcelMap=new ParcelMap({onSelect:parcel=>{selectedParcelId=parcel.id;selectedDetailTab='summary';renderParcelPanel();renderParcelList();},onToast:toast});
  store.subscribe(()=>render());
  bindEvents(); render();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
  window.addEventListener('online',renderNetwork);window.addEventListener('offline',renderNetwork);document.addEventListener('parcelles:gps',event=>updateGpsStatus(event.detail));
  renderNetwork();
}

function state(){return store.snapshot();}
function render(){
  const data=state(); $('#farm-name').textContent=data.exploitation.nom; $('#today-label').textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
  renderDashboard(data);renderHistory(data);renderDataSummaries(data);renderParcelList(data);renderParcelPanel(data);renderSelects(data);
  if(currentView==='map'){parcelMap.render(data);setTimeout(()=>parcelMap.map?.invalidateSize(),10);}
}
function toast(message,type='success'){
  let region=$('.toast-region');if(!region){region=document.createElement('div');region.className='toast-region';document.body.append(region);}const item=document.createElement('div');item.className=`toast ${type==='error'?'error':''}`;item.textContent=message;region.append(item);$('#live-region').textContent=message;setTimeout(()=>item.remove(),4200);
}
function renderNetwork(){const online=navigator.onLine;const pending=state().queue.filter(item=>item.status==='pending').length;const el=$('#network-status');el.textContent=online?`● En ligne${pending?` · ${pending} en attente`:''}`:'● Hors connexion';el.className=`status-pill ${online?'':'offline'}`;}
function updateGpsStatus(detail){const el=$('#network-status');if(detail?.status)el.title=`${detail.status} · précision ± ${Math.round(detail.accuracy)} m`;}
function activeParcels(data=state()){return data.parcelles.filter(item=>!item.deletedAt);}
function activeInterventions(data=state()){return data.interventions.filter(item=>!item.deletedAt);}

function renderDashboard(data){
  const parcels=activeParcels(data),interventions=activeInterventions(data),totalSurface=parcels.reduce((sum,item)=>sum+toNumber(item.surfaceHa),0),todo=parcels.filter(item=>normalize(item.status).includes('faire')).length;
  const cultures=Object.entries(parcels.reduce((acc,item)=>{if(item.culture)acc[item.culture]=(acc[item.culture]||0)+toNumber(item.surfaceHa);return acc;},{})).sort((a,b)=>b[1]-a[1]);
  const totalCost=interventions.reduce((sum,item)=>sum+toNumber(item.cost),0);const recent=interventions.filter(item=>Date.now()-new Date(item.date).getTime()<30*864e5).length;
  $('#dashboard-kpis').innerHTML=[['Surface totale',`${formatNumber(totalSurface)} ha`,`${parcels.length} parcelle${parcels.length!==1?'s':''}`],['Culture dominante',cultures[0]?.[0]||'—',cultures[0]?`${formatNumber(cultures[0][1])} ha`:'À renseigner'],['À faire',todo,todo?'À planifier':'Rien à signaler'],['Interventions',recent,'30 derniers jours'],['Coût enregistré',formatEuro(totalCost),`${interventions.length} intervention${interventions.length!==1?'s':''}`],['Synchronisation',navigator.onLine?'Locale':'Hors connexion',sync.status.configured?'Compte requis':'Non configurée']].map(([label,value,sub])=>`<article class="kpi"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong><small>${escapeHtml(String(sub))}</small></article>`).join('');
  const tasks=parcels.filter(item=>normalize(item.status).includes('faire')).slice(0,6);$('#tasks-list').className='stack-list';$('#tasks-list').innerHTML=tasks.length?tasks.map(parcel=>`<div class="list-row"><div><strong>${escapeHtml(parcel.nom)}</strong><small>${escapeHtml(parcel.culture||'Culture non renseignée')} · ${formatNumber(parcel.surfaceHa)} ha</small></div><button class="small-button" data-action="open-parcel" data-id="${parcel.id}">Ouvrir</button></div>`).join(''):'<div class="empty-state">Aucune parcelle marquée « à faire ».</div>';
  const parcelNames=new Map(parcels.map(item=>[item.id,item.nom]));$('#recent-interventions').className='stack-list';$('#recent-interventions').innerHTML=interventions.sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5).map(item=>`<div class="list-row"><div><strong>${escapeHtml(item.type)}</strong><small>${localDate(item.date)} · ${escapeHtml(parcelNames.get(item.parcelId)||'Parcelle supprimée')}</small></div><span class="badge">${formatEuro(item.cost)}</span></div>`).join('')||'<div class="empty-state">Aucune intervention enregistrée.</div>';
  renderQuality(data);
  if(weatherCache)renderWeather(weatherCache);else $('#weather-content').textContent=data.exploitation.commune?'Prévisions non chargées.':'Ajoutez une commune dans les paramètres pour obtenir les prévisions.';
}
function dataQuality(data){
  const parcels=activeParcels(data),interventions=activeInterventions(data);const issues=[];
  const missingCulture=parcels.filter(item=>!item.culture).length,missingSurface=parcels.filter(item=>!toNumber(item.surfaceHa)).length,missingGeometry=parcels.filter(item=>!item.geometry).length,missingCost=interventions.filter(item=>!toNumber(item.cost)).length;
  if(missingCulture)issues.push(`${missingCulture} parcelle${missingCulture>1?'s':''} sans culture`);if(missingSurface)issues.push(`${missingSurface} parcelle${missingSurface>1?'s':''} sans surface`);if(missingGeometry)issues.push(`${missingGeometry} parcelle${missingGeometry>1?'s':''} sans géométrie`);if(missingCost)issues.push(`${missingCost} intervention${missingCost>1?'s':''} sans coût`);
  const total=Math.max(1,parcels.length*3+interventions.length);const filled=total-missingCulture-missingSurface-missingGeometry-missingCost;return {issues,score:Math.max(0,Math.round(filled/total*100))};
}
function renderQuality(data){const report=dataQuality(data);$('#quality-summary').innerHTML=`<strong>${report.score}% complets</strong><div class="quality-progress"><span style="width:${report.score}%"></span></div><ul class="quality-issues">${report.issues.length?report.issues.map(item=>`<li>⚠ ${escapeHtml(item)}</li>`).join(''):'<li>✓ Aucune anomalie détectée.</li>'}</ul>`;}
function renderWeather(data){if(!data)return;$('#weather-content').innerHTML=`<div class="weather-main"><div class="weather-temperature">${Math.round(data.current.temperature_2m)}°</div><div><strong>${escapeHtml(data.place)}</strong><br><small>Vent ${Math.round(data.current.wind_speed_10m)} km/h · actualisé ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div></div><div class="weather-days">${data.daily.time.slice(0,4).map((day,index)=>`<div class="weather-day"><strong>${new Intl.DateTimeFormat('fr-FR',{weekday:'short'}).format(new Date(day))}</strong><br>${Math.round(data.daily.temperature_2m_max[index])}° / ${Math.round(data.daily.temperature_2m_min[index])}°<br><small>${Math.round(data.daily.precipitation_probability_max[index]||0)}% pluie</small></div>`).join('')}</div>`;}
async function refreshWeather(){const data=state(),farm=data.exploitation;if(!farm.commune){openSettings();toast('Ajoutez une commune pour charger la météo.','error');return;}try{toast('Recherche des prévisions…');const search=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(farm.commune)}&count=1&language=fr&format=json`);const place=(await search.json()).results?.[0];if(!place)throw new Error('Commune introuvable');const api=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&forecast_days=4`);weatherCache={...(await api.json()),place:place.name};renderWeather(weatherCache);toast('Prévisions actualisées.');}catch(error){toast(`Météo indisponible : ${error.message}`,'error');}}

function switchView(view){currentView=view;$$('.view').forEach(item=>item.classList.toggle('is-active',item.id===`view-${view}`));$$('.nav-item').forEach(item=>{const active=item.dataset.view===view;item.classList.toggle('is-active',active);if(active)item.setAttribute('aria-current','page');else item.removeAttribute('aria-current');});if(view==='map'){parcelMap.render(state());setTimeout(()=>parcelMap.map?.invalidateSize(),60);}$('#main').focus({preventScroll:true});}
function filteredParcels(data=state()){
  const query=$('#parcel-search')?.value.trim()||'';const filter=$$('.filter-chip.is-active')[0]?.dataset.filter||'all';let list=activeParcels(data);if(filter==='todo')list=list.filter(item=>normalize(item.status).includes('faire'));if(filter==='selected')list=list.filter(item=>item.id===selectedParcelId);if(!query)return list;
  const tokens=normalize(query).split(/\s+/).filter(Boolean);let minSurface=null;const surfaceMatch=query.match(/>\s*([\d.,]+)\s*(ha)?/i);if(surfaceMatch)minSurface=toNumber(surfaceMatch[1]);
  return list.filter(parcel=>{if(minSurface!==null&&toNumber(parcel.surfaceHa)<=minSurface)return false;const haystack=normalize([parcel.nom,parcel.culture,parcel.commune,parcel.ilot,parcel.sourceId,parcel.cadastral].join(' '));return tokens.filter(token=>!['ha','plus'].includes(token)&&!/^\d/.test(token)).every(token=>haystack.includes(token));});
}
function renderParcelList(data=state()){
  const list=filteredParcels(data);const root=$('#parcel-list');root.innerHTML=list.length?list.map(parcel=>`<button class="parcel-card ${parcel.id===selectedParcelId?'is-selected':''}" data-action="select-parcel" data-id="${parcel.id}"><span class="parcel-card-head"><strong>${escapeHtml(parcel.nom)}</strong>${normalize(parcel.status).includes('faire')?'<span class="badge todo">À faire</span>':''}</span><small>${escapeHtml(parcel.culture||'Culture non renseignée')} · ${formatNumber(parcel.surfaceHa)} ha${parcel.commune?` · ${escapeHtml(parcel.commune)}`:''}</small></button>`).join(''):'<div class="empty-state">Aucune parcelle ne correspond à la recherche.</div>';
}
function renderParcelPanel(data=state()){
  const root=$('#parcel-panel');const parcel=activeParcels(data).find(item=>item.id===selectedParcelId);root.classList.toggle('has-selection',!!parcel);if(!parcel){root.innerHTML='<div class="empty-state">Sélectionnez une parcelle sur la carte ou dans la liste.</div>';return;}const interventions=activeInterventions(data).filter(item=>item.parcelId===parcel.id).sort((a,b)=>new Date(b.date)-new Date(a.date));const last=interventions[0];
  root.innerHTML=`<div class="parcel-detail-header"><button class="modal-close" data-action="close-parcel-panel" aria-label="Fermer la fiche">×</button><h2>${escapeHtml(parcel.nom)}</h2><p>${escapeHtml(parcel.culture||'Culture non renseignée')} · ${formatNumber(parcel.surfaceHa)} ha${parcel.commune?` · ${escapeHtml(parcel.commune)}`:''}</p><div class="detail-actions"><button class="small-button" data-action="new-intervention" data-parcel-id="${parcel.id}">＋ Intervention</button><button class="small-button" data-action="edit-parcel" data-id="${parcel.id}">Modifier</button><button class="small-button" data-action="attach-file" data-id="${parcel.id}">Photo / document</button><button class="small-button danger" data-action="delete-parcel" data-id="${parcel.id}">Supprimer</button></div></div><div class="detail-tabs">${[['summary','Résumé'],['culture','Culture'],['interventions','Interventions'],['history','Historique'],['economy','Économie'],['attachments','Pièces jointes'],['map','Carte']].map(([id,label])=>`<button class="detail-tab ${selectedDetailTab===id?'is-active':''}" data-action="detail-tab" data-tab="${id}">${label}</button>`).join('')}</div><div class="detail-body">${detailBody(parcel,interventions,last,data)}</div>`;
}
function detailBody(parcel,interventions,last,data){
  if(selectedDetailTab==='summary'){
    const lastLabel=last ? `${escapeHtml(last.type)} · ${localDate(last.date)}` : '—';
    return `<dl class="definition-list"><div><dt>Surface</dt><dd>${formatNumber(parcel.surfaceHa)} ha</dd></div><div><dt>Culture</dt><dd>${escapeHtml(parcel.culture||'—')}</dd></div><div><dt>Commune</dt><dd>${escapeHtml(parcel.commune||'—')}</dd></div><div><dt>Îlot</dt><dd>${escapeHtml(parcel.ilot||'—')}</dd></div><div><dt>Statut</dt><dd>${escapeHtml(parcel.status||'À jour')}</dd></div><div><dt>Dernière intervention</dt><dd>${lastLabel}</dd></div></dl>`;
  }
  if(selectedDetailTab==='culture'){
    const rotations=data.rotations.filter(item=>!item.deletedAt&&item.parcelId===parcel.id).sort((a,b)=>String(b.campaignId).localeCompare(String(a.campaignId)));
    const rows=rotations.map(item=>`<li><strong>${escapeHtml(item.culture||'Culture non renseignée')}</strong><small>${escapeHtml(item.campaignId)}</small></li>`).join('');
    return `<p class="form-note">Campagne actuelle : ${campaignFor()}</p>${rows?`<ul class="timeline">${rows}</ul>`:'<div class="empty-state">Aucune rotation enregistrée.</div>'}`;
  }
  if(selectedDetailTab==='interventions'){
    const rows=interventions.slice(0,12).map(item=>{const product=item.product?` · ${escapeHtml(item.product)}`:'';return `<li><strong>${escapeHtml(item.type)}</strong><small>${localDate(item.date)}${product} · ${formatEuro(item.cost)} <button class="text-button" data-action="edit-intervention" data-id="${item.id}">Modifier</button></small></li>`;}).join('');
    return rows?`<ul class="timeline">${rows}</ul>`:'<div class="empty-state">Aucune intervention.</div>';
  }
  if(selectedDetailTab==='history'){
    const history=interventions.map(item=>({date:item.date,text:`${item.type} — ${item.note||'Sans note'}`}));
    data.journal.filter(item=>item.details?.parcelId===parcel.id).forEach(item=>history.push({date:item.createdAt,text:item.message}));
    const rows=history.sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,20).map(item=>`<li><strong>${escapeHtml(item.text)}</strong><small>${localDate(item.date)}</small></li>`).join('');
    return `<ul class="timeline">${rows||'<li>Aucun événement pour cette parcelle.</li>'}</ul>`;
  }
  if(selectedDetailTab==='economy'){
    const costs=interventions.reduce((sum,item)=>sum+toNumber(item.cost),0);const perHa=parcel.surfaceHa?formatEuro(costs/toNumber(parcel.surfaceHa)):'—';const revenue=parcel.revenueHa?formatEuro(parcel.revenueHa):'À renseigner';const margin=parcel.revenueHa?formatEuro(toNumber(parcel.revenueHa)-costs/toNumber(parcel.surfaceHa)):'À renseigner';
    return `<dl class="definition-list"><div><dt>Coût total</dt><dd>${formatEuro(costs)}</dd></div><div><dt>Coût / ha</dt><dd>${perHa}</dd></div><div><dt>Produit / ha</dt><dd>${revenue}</dd></div><div><dt>Marge brute / ha</dt><dd>${margin}</dd></div></dl><p class="form-note">Estimation de gestion : elle ne remplace pas une comptabilité.</p>`;
  }
  if(selectedDetailTab==='attachments'){
    const attachments=[...data.photos,...data.documents].filter(item=>!item.deletedAt&&item.parcelId===parcel.id);const rows=attachments.map(item=>{const type=item.kind==='photo'?'photos':'documents';const label=item.kind==='photo'?'Photo':'Document';return `<div class="list-row"><div><strong>${escapeHtml(item.name||item.nom)}</strong><small>${label} · ${localDate(item.createdAt)}</small></div><button class="small-button danger" data-action="delete-attachment" data-type="${type}" data-id="${item.id}">Retirer</button></div>`;}).join('');
    return rows||'<div class="empty-state">Aucune pièce jointe locale.</div>';
  }
  return parcel.geometry?'<p class="form-note">La parcelle est localisée sur la carte. Utilisez « Cadrer » pour ajuster le zoom.</p>':'<div class="empty-state">Aucune géométrie importée. Ajoutez un GeoJSON lors d’un import.</div>';
}
function renderHistory(data){
  const parcelId=$('#history-parcel')?.value||'',campaign=$('#history-campaign')?.value||'',type=$('#history-type')?.value||'',period=$('#history-period')?.value||'',sort=$('#history-sort')?.value||'recent';const parcels=new Map(activeParcels(data).map(item=>[item.id,item]));let items=activeInterventions(data).filter(item=>(!parcelId||item.parcelId===parcelId)&&(!campaign||item.campaignId===campaign)&&(!type||item.type===type));if(period){const cutoff=Date.now()-Number(period)*864e5;items=items.filter(item=>new Date(item.date)>=cutoff);}items.sort((a,b)=>sort==='old'?new Date(a.date)-new Date(b.date):sort==='cost'?toNumber(b.cost)-toNumber(a.cost):sort==='surface'?toNumber(b.surfaceWorked)-toNumber(a.surfaceWorked):new Date(b.date)-new Date(a.date));$('#history-list').innerHTML=items.length?items.map(item=>`<article class="panel history-entry"><div class="entry-date">${localDate(item.date)}</div><div><div class="entry-title">${escapeHtml(item.type)}</div><div class="entry-meta">${escapeHtml(parcels.get(item.parcelId)?.nom||'Parcelle supprimée')}${item.product?` · ${escapeHtml(item.product)}`:''}${item.operator?` · ${escapeHtml(item.operator)}`:''}</div></div><div class="entry-cost">${formatEuro(item.cost)}<br><button class="text-button" data-action="edit-intervention" data-id="${item.id}">Modifier</button></div></article>`).join(''):'<div class="panel empty-state">Aucune intervention ne correspond aux filtres.</div>';
}
function renderDataSummaries(data){
  const deleted=[...data.parcelles,...data.interventions,...data.materiels,...data.documents,...data.photos].filter(item=>item.deletedAt).length;
  const pending=data.queue.filter(item=>item.status==='pending').length;
  const trash=$('#trash-summary'),syncSummary=$('#sync-summary');
  if(trash)trash.textContent=deleted?`${deleted} élément${deleted>1?'s':''} récupérable${deleted>1?'s':''}.`:'Aucun élément supprimé.';
  if(syncSummary)syncSummary.textContent=sync?.status?.configured?`${sync.status.message} ${pending?`(${pending} opération(s) en attente)`:''}`:'Non configurée. Vos données restent locales.';
}
function renderSelects(data){
  const parcels=activeParcels(data),interventions=activeInterventions(data);function updateSelect(selector,options,placeholder){const select=$(selector);if(!select)return;const current=select.value;select.innerHTML=`<option value="">${placeholder}</option>${options.map(([value,label])=>`<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`).join('')}`;select.value=current;}
  updateSelect('#history-parcel',parcels.map(item=>[item.id,item.nom]),'Toutes les parcelles');updateSelect('#history-campaign',[...new Set(interventions.map(item=>item.campaignId).filter(Boolean))].sort().reverse().map(item=>[item,item]),'Toutes les campagnes');updateSelect('#history-type',[...new Set(interventions.map(item=>item.type).filter(Boolean))].sort().map(item=>[item,item]),'Tous les types');
  const trash=[...data.parcelles,...data.interventions,...data.documents,...data.photos,...data.materiels].filter(item=>item.deletedAt);$('#trash-summary').textContent=trash.length?`${trash.length} élément${trash.length>1?'s':''} récupérable${trash.length>1?'s':''}.`:'Aucun élément supprimé.';$('#sync-summary').textContent=sync.status.message;
}

function bindEvents(){
  document.addEventListener('click',async event=>{
    const control=event.target.closest('[data-action],[data-view],[data-map-open]');if(!control)return;
    if(control.dataset.view){switchView(control.dataset.view);return;}
    if(control.dataset.mapOpen){selectParcel(control.dataset.mapOpen);return;}
    const action=control.dataset.action;const id=control.dataset.id;
    try{
      if(action==='go-dashboard')switchView('dashboard');
      if(action==='select-parcel')selectParcel(id);
      if(action==='open-parcel')openParcel(id);
      if(action==='close-parcel-panel'){selectedParcelId=null;renderParcelPanel();renderParcelList();}
      if(action==='detail-tab'){selectedDetailTab=control.dataset.tab;renderParcelPanel();}
      if(action==='new-parcel')openParcelForm();
      if(action==='edit-parcel')openParcelForm(state().parcelles.find(item=>item.id===id));
      if(action==='delete-parcel')confirmDeletion('parcelles',id);
      if(action==='new-intervention')openInterventionForm(null,control.dataset.parcelId);
      if(action==='edit-intervention')openInterventionForm(state().interventions.find(item=>item.id===id));
      if(action==='choose-import')$('#import-file-input').click();
      if(action==='export-backup')await exportBackup();
      if(action==='choose-restore')$('#restore-file-input').click();
      if(action==='export-interventions')exportInterventions();
      if(action==='open-trash')openTrash();
      if(action==='open-log')openLog();
      if(action==='open-sync')openSync();
      if(action==='open-quality')openQuality();
      if(action==='open-settings')openSettings();
      if(action==='open-calendar')openCalendar();
      if(action==='open-rotations')openRotations();
      if(action==='open-equipment')openEquipment();
      if(action==='open-help')openHelp();
      if(action==='open-field-mode'||action==='toggle-field-mode')openFieldMode();
      if(action==='locate')parcelMap.locate();
      if(action==='toggle-gps-track'){const started=parcelMap.toggleTracking();control.setAttribute('aria-pressed',String(started));control.textContent=started?'Arrêter GPS':'Suivi GPS';}
      if(action==='fit-parcels')parcelMap.fitParcels();
      if(action==='refresh-weather')refreshWeather();
      if(action==='attach-file')openAttachmentForm(id);
      if(action==='delete-attachment')confirmDeletion(control.dataset.type,id);
    }catch(error){console.error(error);toast(error.message||'Une erreur est survenue.','error');}
  });
  document.addEventListener('input',event=>{if(event.target.matches('#parcel-search'))renderParcelList();if(event.target.matches('#settings-search'))filterSettings(event.target.value);});
  document.addEventListener('change',event=>{
    if(event.target.matches('#history-campaign,#history-parcel,#history-type,#history-period,#history-sort'))renderHistory(state());
    if(event.target.matches('.filter-chip')){};
  });
  document.addEventListener('click',event=>{const filter=event.target.closest('.filter-chip');if(filter){$$('.filter-chip').forEach(item=>item.classList.toggle('is-active',item===filter));renderParcelList();}});
  $('#import-file-input').addEventListener('change',handleImportFiles);$('#restore-file-input').addEventListener('change',handleRestoreFile);
  document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();});
}
function selectParcel(id){selectedParcelId=id;selectedDetailTab='summary';switchView('map');parcelMap.select(id);}
function openParcel(id){selectedParcelId=id;selectedDetailTab='summary';switchView('map');parcelMap.select(id);}

function modal(title,description,body,footer='',size=''){
  const root=$('#modal-root');root.classList.add('has-modal');root.innerHTML=`<div class="modal-backdrop" data-action="close-modal"></div><section class="modal ${size}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><div><h2 id="modal-title">${escapeHtml(title)}</h2>${description?`<p>${escapeHtml(description)}</p>`:''}</div><button class="modal-close" data-action="close-modal" aria-label="Fermer">×</button></header><div class="modal-body">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}</section>`;
  root.querySelector('[data-autofocus]')?.focus();
}
function closeModal(){const root=$('#modal-root');root.classList.remove('has-modal');root.innerHTML='';}
document.addEventListener('click',event=>{if(event.target.closest('[data-action="close-modal"]'))closeModal();});

function openParcelForm(parcel=null){
  const isEdit=!!parcel;const p=parcel||{nom:'',surfaceHa:'',culture:'',commune:'',ilot:'',status:'À jour',revenueHa:''};
  modal(isEdit?'Modifier la parcelle':'Nouvelle parcelle',isEdit?'Les changements sont versionnés et peuvent être synchronisés lorsqu’un compte est configuré.':'Les coordonnées peuvent être ajoutées par un import GeoJSON.',`<form id="parcel-form"><div class="form-grid"><label>Nom *<input name="nom" required value="${escapeHtml(p.nom)}" data-autofocus></label><label>Surface (ha)<input name="surfaceHa" type="number" min="0" step="0.01" value="${p.surfaceHa??''}"></label><label>Culture<input name="culture" value="${escapeHtml(p.culture||'')}"></label><label>Commune<input name="commune" value="${escapeHtml(p.commune||'')}"></label><label>Îlot<input name="ilot" value="${escapeHtml(p.ilot||'')}"></label><label>Statut<select name="status">${['À jour','À faire','En cours','Terminé'].map(value=>`<option ${p.status===value?'selected':''}>${value}</option>`).join('')}</select></label><label class="span-2">Produit estimé (€/ha)<input name="revenueHa" type="number" min="0" step="0.01" value="${p.revenueHa??''}"></label></div></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="save-parcel">${isEdit?'Enregistrer':'Créer la parcelle'}</button>`);
  $('#save-parcel').onclick=async()=>{const form=$('#parcel-form');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));await store.upsert('parcelles',{...p,...values,surfaceHa:toNumber(values.surfaceHa),revenueHa:toNumber(values.revenueHa)},{label:`${isEdit?'Parcelle modifiée':'Parcelle créée'} : ${values.nom}`});selectedParcelId=isEdit?p.id:store.list('parcelles').at(-1)?.id;closeModal();toast(isEdit?'Parcelle mise à jour.':'Parcelle créée.');};
}
function openInterventionForm(intervention=null,parcelId=null){
  const data=state(),parcels=activeParcels(data);if(!parcels.length){toast('Créez ou importez d’abord une parcelle.','error');return;}const isEdit=!!intervention;const item=intervention||{parcelId:parcelId||selectedParcelId||parcels[0].id,date:isoDate(Date.now()),type:'',product:'',dose:'',doseUnit:'',surfaceWorked:'',duration:'',fuel:'',operator:'',equipmentId:'',weather:'',cost:'',note:''};
  modal(isEdit?'Modifier l’intervention':'Nouvelle intervention','Tous les champs utiles au carnet parcellaire sont conservés dans un modèle unique.',`<form id="intervention-form"><div class="form-grid"><label>Parcelle *<select name="parcelId" required>${parcels.map(parcel=>`<option value="${parcel.id}" ${item.parcelId===parcel.id?'selected':''}>${escapeHtml(parcel.nom)}</option>`).join('')}</select></label><label>Date *<input name="date" type="date" required value="${isoDate(item.date)}"></label><label>Type *<input name="type" required placeholder="Semis, fertilisation…" value="${escapeHtml(item.type)}"></label><label>Culture<input name="culture" value="${escapeHtml(item.culture||'')}"></label><label>Produit<input name="product" value="${escapeHtml(item.product||'')}"></label><label>Dose<input name="dose" value="${escapeHtml(item.dose||'')}"></label><label>Surface travaillée (ha)<input name="surfaceWorked" type="number" min="0" step="0.01" value="${item.surfaceWorked??''}"></label><label>Durée (h)<input name="duration" type="number" min="0" step="0.1" value="${item.duration??''}"></label><label>Carburant (L)<input name="fuel" type="number" min="0" step="0.1" value="${item.fuel??''}"></label><label>Coût total (€)<input name="cost" type="number" min="0" step="0.01" value="${item.cost??''}"></label><label>Opérateur<input name="operator" value="${escapeHtml(item.operator||'')}"></label><label>Matériel<select name="equipmentId"><option value="">Non renseigné</option>${data.materiels.filter(x=>!x.deletedAt).map(machine=>`<option value="${machine.id}" ${item.equipmentId===machine.id?'selected':''}>${escapeHtml(machine.nom)}</option>`).join('')}</select></label><label>Conditions météo<input name="weather" value="${escapeHtml(item.weather||'')}"></label><label>Pièce jointe <input disabled value="Ajout après enregistrement"></label><label class="span-2">Note<textarea name="note">${escapeHtml(item.note||'')}</textarea></label></div></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button>${isEdit?'<button class="button secondary" id="remove-intervention">Supprimer</button>':''}<button class="button primary" id="save-intervention">${isEdit?'Enregistrer':'Créer l’intervention'}</button>`);
  $('#save-intervention').onclick=async()=>{const form=$('#intervention-form');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));const entity={...item,...values,cost:toNumber(values.cost),surfaceWorked:toNumber(values.surfaceWorked),duration:toNumber(values.duration),fuel:toNumber(values.fuel),campaignId:campaignFor(values.date)};await store.upsert('interventions',entity,{label:`${isEdit?'Intervention modifiée':'Intervention créée'} : ${values.type}`});closeModal();toast(isEdit?'Intervention mise à jour.':'Intervention enregistrée.');};
  $('#remove-intervention')?.addEventListener('click',()=>confirmDeletion('interventions',item.id));
}
function confirmDeletion(type,id){
  const label={parcelles:'cette parcelle et sa fiche',interventions:'cette intervention',documents:'ce document',photos:'cette photo',materiels:'ce matériel'}[type]||'cet élément';modal('Placer dans la corbeille','Vous pourrez le restaurer depuis le Centre de données.',`<div class="notice warning">Souhaitez-vous retirer ${label} ? Les autres données liées ne sont pas effacées.</div>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="confirm-delete">Placer dans la corbeille</button>`,'small');$('#confirm-delete').onclick=async()=>{await store.remove(type,id);closeModal();toast('Élément déplacé dans la corbeille.');};
}

async function handleImportFiles(event){
  const files=[...event.target.files];event.target.value='';if(!files.length)return;
  try{modal('Analyse de l’import','Les données ne sont pas encore modifiées.',`<div class="empty-state">Analyse de ${files.length} fichier(s)…</div>`,'','small');importPreview=await inspectFiles(files,state());if(!importPreview.sources.length){modal('Import impossible','Aucune source valide n’a été détectée.',importPreview.invalid.map(item=>`<div class="notice danger">${escapeHtml(item.file)} : ${escapeHtml(item.message)}</div>`).join(''),'<button class="button primary" data-action="close-modal">Fermer</button>','small');return;}modal('Prévisualisation de l’import','Vérifiez les données, les doublons et la projection avant de confirmer.',`${importPreviewHtml(importPreview)}<label class="field-label" style="margin-top:16px">Pour les doublons<select id="import-strategy"><option value="merge">Fusionner les valeurs renseignées</option><option value="replace">Remplacer par la ligne importée</option><option value="ignore">Ignorer les doublons</option><option value="new">Créer de nouvelles parcelles</option></select></label>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="apply-import">Importer les données validées</button>`);$('#apply-import').onclick=async()=>{const button=$('#apply-import');button.disabled=true;button.textContent='Import en cours…';try{const result=await applyImport(importPreview,store,$('#import-strategy').value);closeModal();toast(`Import terminé : ${result.created} création(s), ${result.updated} mise(s) à jour.`);switchView('map');}catch(error){button.disabled=false;button.textContent='Importer les données validées';toast(error.message,'error');}};}catch(error){closeModal();toast(`Analyse impossible : ${error.message}`,'error');}}
async function exportBackup(){try{const backup=await makeBackup(state());download(`parcelles-sauvegarde-${isoDate(backup.createdAt)}.json`,JSON.stringify(backup,null,2));await store.mutate('Sauvegarde complète exportée.',()=>{},{queue:false,kind:'backup'});toast('Sauvegarde complète téléchargée.');}catch(error){toast(`Sauvegarde impossible : ${error.message}`,'error');}}
function exportInterventions(){const csv=exportCsv(state());download(`parcelles-interventions-${isoDate(Date.now())}.csv`,csv,'text/csv;charset=utf-8');toast('Historique CSV téléchargé.');}
async function handleRestoreFile(event){
  const file=event.target.files[0];event.target.value='';if(!file)return;try{const preview=await validateBackup(JSON.parse(await file.text()));const c=preview.meta.counts;modal('Prévisualiser la restauration','L’état actuel sera d’abord sauvegardé automatiquement.',`<div class="preview-summary"><div class="preview-stat"><strong>${c.parcelles||0}</strong><small>parcelles</small></div><div class="preview-stat"><strong>${c.interventions||0}</strong><small>interventions</small></div><div class="preview-stat"><strong>${c.photos||0}</strong><small>photos</small></div></div><div class="notice">Sauvegarde du ${localDateTime(preview.meta.createdAt)} · format v${preview.meta.formatVersion||'inconnu'} · intégrité vérifiée.</div><p class="form-note">La restauration remplacera les données de cet appareil. Une sauvegarde de l’état actuel sera téléchargée avant l’opération.</p>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="confirm-restore">Sauvegarder puis restaurer</button>`);$('#confirm-restore').onclick=async()=>{const before=await makeBackup(state());download(`parcelles-avant-restauration-${isoDate(Date.now())}.json`,JSON.stringify(before,null,2));await store.replaceState(preview.data);closeModal();toast('Sauvegarde restaurée en toute sécurité.');};}catch(error){toast(`Restauration refusée : ${error.message}`,'error');}}
function openTrash(){const data=state();const types=['parcelles','interventions','materiels','documents','photos'];const rows=types.flatMap(type=>data[type].filter(item=>item.deletedAt).map(item=>({type,item})));modal('Corbeille','Les éléments restent récupérables ici.',rows.length?`<div class="trash-list">${rows.map(({type,item})=>`<div class="list-row"><div><strong>${escapeHtml(item.nom||item.name||item.type||'Élément')}</strong><small>${type.slice(0,-1)} · supprimé le ${localDate(item.deletedAt)}</small></div><button class="small-button" data-restore-type="${type}" data-restore-id="${item.id}">Restaurer</button></div>`).join('')}</div>`:'<div class="empty-state">La corbeille est vide.</div>','<button class="button secondary" data-action="close-modal">Fermer</button>');$$('[data-restore-type]').forEach(button=>button.onclick=async()=>{await store.restore(button.dataset.restoreType,button.dataset.restoreId);closeModal();toast('Élément restauré.');});}
function openLog(){const entries=state().journal;modal('Journal système','Les 500 événements les plus récents sont conservés localement.',entries.length?`<ul class="log-list">${entries.slice(0,100).map(item=>`<li><time>${localDateTime(item.createdAt)}</time><span><strong>${escapeHtml(item.message)}</strong><br><small>${escapeHtml(item.type)}</small></span></li>`).join('')}</ul>`:'<div class="empty-state">Aucun événement enregistré.</div>','<button class="button secondary" data-action="close-modal">Fermer</button>');}
function openSync(){const data=state();const pending=data.queue.filter(item=>item.status==='pending').length;modal('Centre de synchronisation','Les données locales sont indépendantes de tout compte tant que vous ne configurez pas une authentification.',`<div class="sync-status"><span class="sync-dot ${sync.status.connected?'good':''}"></span><div><strong>${sync.status.connected?'Connecté':'Local uniquement'}</strong><br><small>${escapeHtml(sync.status.message)}</small></div></div><dl class="definition-list" style="margin-top:14px"><div><dt>Dernière synchronisation</dt><dd>${data.metadata.lastSyncAt?localDateTime(data.metadata.lastSyncAt):'Aucune'}</dd></div><div><dt>Modifications en attente</dt><dd>${pending}</dd></div><div><dt>Conflits</dt><dd>0</dd></div><div><dt>Documents</dt><dd>Locaux par défaut</dd></div></dl><div class="notice warning" style="margin-top:14px">La synchronisation exige une authentification utilisateur. Elle écrit chaque parcelle, intervention ou document séparément et affiche les conflits au lieu d’écraser silencieusement une version distante.</div>`,`<button class="button secondary" data-action="close-modal">Fermer</button>`);}
function openQuality(){const report=dataQuality(state());modal('Centre de qualité des données','Repérez les informations à compléter avant une exportation ou une synchronisation.',`<div class="quality-summary"><strong>${report.score}% complets</strong><div class="quality-progress"><span style="width:${report.score}%"></span></div><ul class="quality-issues">${report.issues.length?report.issues.map(item=>`<li>⚠ ${escapeHtml(item)}</li>`).join(''):'<li>✓ Aucune anomalie détectée.</li>'}</ul></div><div class="notice">Les données importées sont validées avant l’enregistrement. Les incohérences de géométrie restent signalées dans la prévisualisation.</div>`,`<button class="button secondary" data-action="close-modal">Fermer</button>`);}
function openAttachmentForm(parcelId){
  modal('Ajouter une pièce jointe','Les fichiers sont stockés localement dans IndexedDB. Ils ne quittent pas votre appareil sans configuration de stockage cloud.',`<form id="attachment-form"><label class="field-label">Fichier<input name="file" type="file" required accept="image/*,.pdf,.doc,.docx,.xls,.xlsx"></label><label class="field-label" style="margin-top:12px">Commentaire<input name="note" maxlength="240"></label></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="save-attachment">Enregistrer localement</button>`,'small');$('#save-attachment').onclick=async()=>{const form=$('#attachment-form');const file=form.file.files[0];if(!file){form.file.focus();return;}try{const kind=file.type.startsWith('image/')?'photos':'documents';const id=uid(kind.slice(0,-1));await store.storage.blobPut(id,file);await store.upsert(kind,{id,parcelId,name:file.name,mimeType:file.type,size:file.size,note:form.note.value,kind:kind==='photos'?'photo':'document',source:'local'},{label:`Pièce jointe ajoutée : ${file.name}`,queue:false});closeModal();toast('Pièce jointe enregistrée localement.');}catch(error){toast(error.message,'error');}};
}

function openSettings(){
  const data=state(),farm=data.exploitation,prefs=data.preferences;modal('Paramètres','Recherchez un réglage ou ouvrez une catégorie.',`<label class="search-field"><span class="sr-only">Rechercher dans les paramètres</span><input id="settings-search" type="search" placeholder="Rechercher dans les paramètres" data-autofocus><span aria-hidden="true">⌕</span></label><form id="settings-form"><section class="settings-section" data-settings="compte exploitation"><h3>Exploitation</h3><div class="form-grid"><label>Nom de l’exploitation<input name="nom" value="${escapeHtml(farm.nom)}"></label><label>Commune (météo)<input name="commune" value="${escapeHtml(farm.commune||'')}"></label><label>Latitude (facultatif)<input name="latitude" type="number" step="0.00001" value="${farm.latitude??''}"></label><label>Longitude (facultatif)<input name="longitude" type="number" step="0.00001" value="${farm.longitude??''}"></label></div></section><section class="settings-section" data-settings="carte gps confidentialité"><h3>Carte, GPS & confidentialité</h3><div class="form-grid"><label>Fond de carte<select name="mapLayer"><option value="osm" ${prefs.mapLayer==='osm'?'selected':''}>OpenStreetMap</option></select></label><label>Apparence<select name="theme"><option value="system" ${prefs.theme==='system'?'selected':''}>Système</option><option value="light" ${prefs.theme==='light'?'selected':''}>Clair</option></select></label><label><input name="gpsConsent" type="checkbox" ${prefs.gpsConsent?'checked':''}> Autoriser le GPS après action</label><label><input name="autoBackup" type="checkbox" ${prefs.autoBackup?'checked':''}> Sauvegarde locale quotidienne</label></div><p class="form-note">La position GPS n’est jamais envoyée automatiquement.</p></section><section class="settings-section" data-settings="notifications alertes"><h3>Notifications</h3><p class="form-note">L’autorisation est demandée uniquement lorsque vous cliquez sur le bouton ci-dessous.</p><button type="button" class="button secondary" id="ask-notifications">Autoriser les notifications locales</button></section><section class="settings-section" data-settings="données synchronisation hors connexion"><h3>Données & synchronisation</h3><div class="notice warning">Authentification et règles Firebase par utilisateur requises avant d’activer une synchronisation. Aucun secret n’est enregistré ici.</div></section><section class="settings-section" data-settings="aide a propos"><h3>À propos</h3><p class="form-note">Parcelles 2.0 · format de données v3 · application locale mobile d’abord.</p></section></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="save-settings">Enregistrer</button>`);
  $('#save-settings').onclick=async()=>{const form=$('#settings-form');const values=Object.fromEntries(new FormData(form));await store.setExploitation({nom:values.nom.trim()||'Mon exploitation',commune:values.commune.trim(),latitude:values.latitude?toNumber(values.latitude):null,longitude:values.longitude?toNumber(values.longitude):null});await store.setPreferences({mapLayer:values.mapLayer,theme:values.theme,gpsConsent:form.gpsConsent.checked,autoBackup:form.autoBackup.checked});closeModal();toast('Paramètres enregistrés.');};
  $('#ask-notifications').onclick=async()=>{if(!('Notification'in window)){toast('Les notifications ne sont pas prises en charge.','error');return;}const permission=await Notification.requestPermission();if(permission==='granted'){await store.setPreferences({notifications:true});new Notification('Parcelles',{body:'Les notifications locales sont activées.'});toast('Notifications locales activées.');}else toast('Autorisation de notification non accordée.','error');};
}
function filterSettings(query){const needle=normalize(query);$$('.settings-section').forEach(section=>section.classList.toggle('hidden',needle&&!normalize(section.dataset.settings+' '+section.textContent).includes(needle)));}
function openCalendar(){
  const data=state(),parcels=new Map(activeParcels(data).map(item=>[item.id,item]));
  const items=activeInterventions(data).sort((a,b)=>new Date(a.date)-new Date(b.date));
  const content=items.length
    ? `<ul class="timeline">${items.slice(0,60).map(item=>{
      const parcelName=parcels.get(item.parcelId)?.nom||'Parcelle supprimée';
      const note=item.note?` · ${escapeHtml(item.note)}`:'';
      return `<li><strong>${escapeHtml(item.type)} — ${escapeHtml(parcelName)}</strong><small>${localDate(item.date)} · campagne ${escapeHtml(item.campaignId||campaignFor(item.date))}${note}</small></li>`;
    }).join('')}</ul>`
    : '<div class="empty-state">Ajoutez une intervention pour alimenter le calendrier.</div>';
  modal('Calendrier cultural','Les interventions sont automatiquement rattachées à leur campagne agricole.',content,`<button class="button secondary" data-action="close-modal">Fermer</button><button class="button primary" id="calendar-add">＋ Intervention</button>`);
  $('#calendar-add').onclick=()=>{closeModal();openInterventionForm();};
}
function openRotations(){const data=state(),parcels=activeParcels(data);const rotations=data.rotations.filter(item=>!item.deletedAt);modal('Cultures & rotations','L’assolement est construit à partir de vos rotations et de la culture courante.',`<div class="table-wrap"><table><thead><tr><th>Parcelle</th><th>Culture actuelle</th><th>Historique</th><th></th></tr></thead><tbody>${parcels.map(parcel=>{const history=rotations.filter(item=>item.parcelId===parcel.id).sort((a,b)=>String(b.campaignId).localeCompare(String(a.campaignId)));return `<tr><td>${escapeHtml(parcel.nom)}</td><td>${escapeHtml(parcel.culture||'—')}</td><td>${history.length?history.map(item=>`${escapeHtml(item.campaignId)} : ${escapeHtml(item.culture)}`).join('<br>'):'—'}</td><td><button class="text-button" data-rotation-parcel="${parcel.id}">Ajouter</button></td></tr>`;}).join('')}</tbody></table></div>`,`<button class="button secondary" data-action="close-modal">Fermer</button>`);$$('[data-rotation-parcel]').forEach(button=>button.onclick=()=>openRotationForm(button.dataset.rotationParcel));}
function openRotationForm(parcelId){const parcel=store.get('parcelles',parcelId);modal('Ajouter une rotation',parcel.nom,`<form id="rotation-form" class="form-grid"><label>Campagne<input name="campaignId" required value="${campaignFor()}"></label><label>Culture<input name="culture" required value="${escapeHtml(parcel.culture||'')}"></label></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="save-rotation">Enregistrer</button>`,'small');$('#save-rotation').onclick=async()=>{const form=$('#rotation-form');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));await store.upsert('rotations',{parcelId,campaignId:values.campaignId,culture:values.culture},{label:`Rotation ajoutée : ${parcel.nom}`});closeModal();toast('Rotation enregistrée.');};}
function openEquipment(){const machines=state().materiels.filter(item=>!item.deletedAt);modal('Matériel','Compteurs, coûts horaires et entretiens peuvent être associés à une intervention.',`<div class="stack-list">${machines.length?machines.map(machine=>`<div class="list-row"><div><strong>${escapeHtml(machine.nom)}</strong><small>Compteur : ${formatNumber(machine.currentMeter)} h · coût horaire : ${formatEuro(machine.hourlyCost)}</small></div><button class="small-button" data-edit-equipment="${machine.id}">Modifier</button></div>`).join(''):'<div class="empty-state">Aucun matériel enregistré.</div>'}</div>`,`<button class="button secondary" data-action="close-modal">Fermer</button><button class="button primary" id="new-equipment">＋ Matériel</button>`);$('#new-equipment').onclick=()=>openEquipmentForm();$$('[data-edit-equipment]').forEach(button=>button.onclick=()=>openEquipmentForm(store.get('materiels',button.dataset.editEquipment)));}
function openEquipmentForm(machine=null){const item=machine||{nom:'',initialMeter:'',currentMeter:'',hourlyCost:'',actualFuel:'',theoreticalFuel:'',maintenanceDue:'',insurance:'',amortization:''};modal(machine?'Modifier le matériel':'Nouveau matériel','Les alertes d’entretien sont basées sur le compteur actuel et l’échéance saisie.',`<form id="equipment-form"><div class="form-grid"><label>Nom *<input name="nom" required value="${escapeHtml(item.nom)}" data-autofocus></label><label>Compteur initial (h)<input name="initialMeter" type="number" min="0" value="${item.initialMeter??''}"></label><label>Compteur actuel (h)<input name="currentMeter" type="number" min="0" value="${item.currentMeter??''}"></label><label>Entretien prévu à (h)<input name="maintenanceDue" type="number" min="0" value="${item.maintenanceDue??''}"></label><label>Coût horaire (€)<input name="hourlyCost" type="number" min="0" step=".01" value="${item.hourlyCost??''}"></label><label>Consommation réelle (L/h)<input name="actualFuel" type="number" min="0" step=".1" value="${item.actualFuel??''}"></label><label>Assurance annuelle (€)<input name="insurance" type="number" min="0" step=".01" value="${item.insurance??''}"></label><label>Amortissement annuel (€)<input name="amortization" type="number" min="0" step=".01" value="${item.amortization??''}"></label></div></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="save-equipment">Enregistrer</button>`);$('#save-equipment').onclick=async()=>{const form=$('#equipment-form');if(!form.reportValidity())return;const raw=Object.fromEntries(new FormData(form));for(const key of Object.keys(raw))if(key!=='nom')raw[key]=toNumber(raw[key]);await store.upsert('materiels',{...item,...raw},{label:`Matériel ${machine?'modifié':'créé'} : ${raw.nom}`});closeModal();toast('Matériel enregistré.');};}
function openHelp(){modal('Aide','Mode d’emploi rapide de l’application.',`<h3>Importer en sécurité</h3><p>Choisissez CSV, Excel, GeoJSON ou un ZIP cartographique complet. L’aperçu présente les lignes, surfaces, colonnes inconnues, géométries invalides et doublons avant validation.</p><h3>Hors connexion</h3><p>Les modifications sont enregistrées dans la base locale de cet appareil. L’indicateur d’en-tête précise l’état du réseau. La synchronisation est inactive tant qu’un compte sécurisé n’est pas configuré.</p><h3>Sauvegarder</h3><p>Utilisez Centre de données → Créer une sauvegarde avant une opération importante. Une restauration vérifie le format, l’intégrité et télécharge l’état actuel avant remplacement.</p><h3>iPhone / fichiers</h3><p>Pour les couches SIG, privilégiez un ZIP contenant SHP, SHX, DBF et PRJ ou un GeoJSON. L’accès aux fichiers dépend de l’app Fichiers et du navigateur.</p>`,`<button class="button primary" data-action="close-modal">Compris</button>`);}
function openFieldMode(){
  if(fieldModeOpen)return;fieldModeOpen=true;const overlay=document.createElement('section');overlay.id='field-mode';overlay.className='field-mode';overlay.innerHTML=`<div class="field-mode-inner"><div class="view-heading"><div><p class="eyebrow">Mode terrain</p><h1>Sur le terrain</h1></div><button class="icon-button" id="close-field-mode" aria-label="Quitter le mode terrain">×</button></div><div id="field-gps" class="field-location"><strong>Position non demandée</strong><span>Utilisez « Me localiser » quand vous êtes prêt.</span></div><div class="field-actions"><button id="field-locate"><span>⌖</span>Me localiser</button><button id="field-intervention"><span>＋</span>Intervention</button><button id="field-photo"><span>▣</span>Photo</button><button id="field-map"><span>⌖</span>Carte</button></div><article class="panel"><div class="panel-heading"><h2>Parcelles proches</h2></div><div id="field-nearby" class="stack-list"><div class="empty-state">La position reste sur cet appareil.</div></div></article></div>`;document.body.append(overlay);$('#close-field-mode').onclick=()=>{overlay.remove();fieldModeOpen=false;};$('#field-locate').onclick=()=>parcelMap.locate();$('#field-intervention').onclick=()=>{overlay.remove();fieldModeOpen=false;openInterventionForm(null,selectedParcelId);};$('#field-photo').onclick=()=>{if(!selectedParcelId){toast('Sélectionnez d’abord une parcelle sur la carte.','error');return;}overlay.remove();fieldModeOpen=false;openAttachmentForm(selectedParcelId);};$('#field-map').onclick=()=>{overlay.remove();fieldModeOpen=false;switchView('map');};document.addEventListener('parcelles:gps',updateFieldGps,{once:true});
}
function updateFieldGps(event){const detail=event.detail||event;if(!fieldModeOpen)return;const root=$('#field-gps');if(root)root.innerHTML=`<strong>${escapeHtml(detail.status||'Position GPS')}</strong><span>Précision ± ${Math.round(detail.accuracy)} m · position conservée localement</span>`;const nearby=activeParcels(state()).filter(parcel=>parcel.geometry).slice(0,5);const list=$('#field-nearby');if(list)list.innerHTML=nearby.length?nearby.map(parcel=>`<div class="list-row"><div><strong>${escapeHtml(parcel.nom)}</strong><small>${escapeHtml(parcel.culture||'Culture non renseignée')} · ${formatNumber(parcel.surfaceHa)} ha</small></div><button class="small-button" data-field-parcel="${parcel.id}">Ouvrir</button></div>`).join(''):'<div class="empty-state">Aucune parcelle géolocalisée.</div>';$$('[data-field-parcel]').forEach(button=>button.onclick=()=>{const overlay=$('#field-mode');overlay?.remove();fieldModeOpen=false;openParcel(button.dataset.fieldParcel);});}

init().catch(error=>{console.error(error);document.body.innerHTML=`<main style="padding:2rem;font-family:system-ui"><h1>Impossible de démarrer Parcelles</h1><p>${escapeHtml(error.message)}</p></main>`;});
