import {readApplicationGeoJson,analyzeCoverage} from './application-coverage.js';
import {escapeHtml as e,uid,downloadBlob} from './utils.js';import {parseYieldCsv} from './yield.js';import {applicationPoints,compareApplication} from './application-map.js';import {farmRecords} from './farm-records.js';import {prescriptionGeoJson} from './prescriptions.js';
let scope='',source=null,raw=null,config=null,measures=null,selectedPlan=null,coverage=null;
export async function applicationAction(action,control,c){if(!['applied','applied-read','applied-preview','applied-save','applied-open','applied-map','applied-plan-map','applied-coverage-map'].includes(action))return false;const{host,show,button,data,parcel,fmt,featuresOnMap}=c,{store}=host,p=parcel();if(!p?.geometry)throw Error('Parcelle avec contour nécessaire.');if(scope!==store.workspaceContext().key){scope=store.workspaceContext().key;source=raw=config=measures=selectedPlan=coverage=null;}const plans=farmRecords(data(),'prescription').filter(r=>r.parcelId===p.id);
 const switchLayer=()=>{if(!selectedPlan)return;const panel=document.querySelector('.satellite-map-label');if(!panel)return;const actions=document.createElement('div');actions.className='satellite-actions';actions.innerHTML=button('applied-map','Réalisé')+button('applied-plan-map','Prévu');panel.append(actions);};
 const reviewCoverage=()=>show('Couverture réellement relevée',`<p>Résolution ${coverage.resolution} m · valeurs estimées</p><p>Cible parcelle : ${fmt(coverage.targetHa)} ha ; couvert : ${fmt(coverage.coveredHa)} ha ; manque : ${fmt(coverage.missingHa)} ha ; recouvrement : ${fmt(coverage.overlapHa)} ha.</p><p>${e(coverage.method)}</p>`,button('applied-coverage-map','Carte couvert / manque / recouvrement')+(raw?button('applied-save','Valider cet import'):''));const review=()=>show('Prescription / relevé appliqué',`<p>${measures.points.length} points utilisés · ${measures.excluded.length} ignorés. Moyenne des points, sans surface couverte ni détection fiable de manques/recouvrements.</p>${selectedPlan?compareApplication(measures.points,selectedPlan.zoneSnapshot,selectedPlan.plan).map(r=>`<p>Zone ${e(r.id)} : prévu ${fmt(r.planned)}, relevé ${fmt(r.actual)} ${e(config.unit)} · ${r.samples} mesures · ${r.observedCells}/${r.cells} cellules observées</p>`).join(''):'<p>Aucune préconisation comparable sélectionnée.</p>'}<div class="satellite-actions">${button('applied-map','Afficher le relevé')}${selectedPlan?button('applied-plan-map','Afficher la préconisation'):''}</div>`,raw?button('applied-save','Valider cet import'): '');
 if(action==='applied'){show('Carte réellement appliquée',`<p>CSV WGS84 : positions et doses mesurées. Pour les surfaces et recouvrements : GeoJSON de polygones de passages, avec properties.rate ; chaque polygone doit représenter un passage distinct.</p><input id="applied-file" type="file" accept=".csv,.geojson,.json"><label>Résolution couverture (m)<select id="coverage-resolution"><option>5</option><option>1</option><option>2</option><option>10</option><option>20</option></select></label>${button('applied-read','Lire le fichier')}<h3>Relevés conservés</h3>${activeDocs().map(d=>`<p>${e(d.name)} ${button('applied-open','Consulter',`data-id="${e(d.id)}"`)}</p>`).join('')}`);}
 else if(action==='applied-read'){raw=document.querySelector('#applied-file').files[0];if(!raw||raw.size>8*1024*1024)throw Error('Fichier de 8 Mo maximum.');if(/\.(geojson|json)$/i.test(raw.name)){source=readApplicationGeoJson(await raw.text());config={format:'footprints',resolution:Number(document.querySelector('#coverage-resolution').value)};coverage=analyzeCoverage(p,source,config);measures={};selectedPlan=null;reviewCoverage();return true;}coverage=null;source=parseYieldCsv(await raw.text());show('Colonnes du relevé',`<form id="applied-form" class="form-grid">${[['longitude','Longitude'],['latitude','Latitude'],['rate','Dose appliquée']].map(([key,label])=>`<label>${label}<select name="${key}"><option value="">Choisir</option>${source.headers.map(h=>`<option>${e(h)}</option>`).join('')}</select></label>`).join('')}<label>Unité<select name="unit">${['kg/ha','L/ha','graines/ha'].map(u=>`<option>${u}</option>`).join('')}</select></label><label>Préconisation<select name="plan"><option value="">Sans comparaison</option>${plans.map(r=>`<option value="${e(r.id)}">${e(r.name)}</option>`).join('')}</select></label></form>`,button('applied-preview','Calculer l’aperçu'));}
 else if(action==='applied-preview'){config=Object.fromEntries(new FormData(document.querySelector('#applied-form')));selectedPlan=plans.find(r=>r.id===config.plan)||null;if(selectedPlan&&selectedPlan.plan.unit!==config.unit)throw Error('Les unités de la préconisation et du relevé doivent correspondre.');measures=applicationPoints(source,config,p);if(!measures.points.length)throw Error('Aucune mesure valide dans cette parcelle.');review();}
 else if(action==='applied-save'){if(!raw||!config||!measures)throw Error('Prévisualisez le relevé.');if(store.writeGuard&&!store.writeGuard({entity:'documents',action:'create'}))throw Error('Import non autorisé.');const id=uid('application');await store.storage.blobPut(id,raw);try{if(scope!==store.workspaceContext().key)throw Error('Exploitation changée.');await store.upsert('documents',{id,name:raw.name,mimeType:config.format==='footprints'?'application/geo+json':'text/csv',parcelId:p.id,category:'Carte appliquée',applicationMap:{version:1,...config,pointCount:config.format==='footprints'?source.length:source.rows.length}},{label:'Carte appliquée validée.'});raw=null;if(coverage)reviewCoverage();else review();}catch(err){await store.storage.blobDelete(id);throw err;}}
 else if(action==='applied-open'){const doc=store.get('documents',control.dataset.id),blob=await store.storage.blobGet(doc.id);if(!blob)throw Error('Brut absent de cet appareil : synchronisez les pièces jointes.');config=doc.applicationMap;if(config.format==='footprints'){source=readApplicationGeoJson(await blob.text());coverage=analyzeCoverage(p,source,config);raw=null;reviewCoverage();return true;}coverage=null;source=parseYieldCsv(await blob.text());selectedPlan=plans.find(r=>r.id===config.plan)||null;measures=applicationPoints(source,config,p);raw=null;review();}
 else if(action==='applied-coverage-map'){featuresOnMap(coverage.cells,'Couverture estimée · maille '+coverage.resolution+' m');}
 else if(action==='applied-map'){featuresOnMap(measures.points.slice(0,20000).map(r=>({type:'Feature',geometry:{type:'Point',coordinates:[r.longitude,r.latitude]},properties:{dose:r.rate,unite:config.unit,color:'#2f82b0'}})),'Doses réellement relevées');switchLayer();}
 else if(action==='applied-plan-map'){featuresOnMap(prescriptionGeoJson(selectedPlan.zoneSnapshot,selectedPlan.plan).features,'Préconisation de référence');switchLayer();}
 return true;
 function activeDocs(){return(data().documents||[]).filter(d=>!d.deletedAt&&d.parcelId===p.id&&d.applicationMap?.version===1);}
}
