import {requiredStock as stockRequirement} from './work-effects.js';
import {campaignFor,geometryCentroid,haversineMeters,normalize} from './utils.js';
import {active,completed} from './farm-memory.js';
import {isPending} from './home-priorities.js';
import {weatherWindows,WEATHER_RULES} from './weather-decision.js';
const number=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
export function workDuration(work,state){if(number(work.duration)!==null&&work.duration>0)return{hours:work.duration,confidence:'Durée saisie',samples:0};const p=active(state,'parcelles').find(p=>p.id===work.parcelId),area=number(work.surfaceWorked)??number(p?.surfaceHa);const history=active(state,'interventions').filter(w=>completed(w)&&normalize(w.type)===normalize(work.type)&&w.duration>0&&w.surfaceWorked>0&&(!work.equipmentId||w.equipmentId===work.equipmentId)).map(w=>w.duration/w.surfaceWorked).sort((a,b)=>a-b);return{hours:area>0&&history.length?area*history[Math.floor(history.length/2)]:null,confidence:history.length>=3?'Estimation historique':'Données insuffisantes',samples:history.length};}
export function campaignProgress(state,campaign){const types=new Map();for(const w of active(state,'interventions').filter(w=>w.status!=='Annulé'&&(w.campaignId||((w.plannedDate||w.date)?campaignFor(w.plannedDate||w.date):null))===campaign)){const p=active(state,'parcelles').find(p=>p.id===w.parcelId),area=number(w.surfaceWorked)??number(p?.surfaceHa),row=types.get(w.type)||{type:w.type,planned:0,done:0,missingArea:0,remainingHours:0,unknownHours:0};if(area===null)row.missingArea++;else{row.planned+=area;if(completed(w))row.done+=area;}if(isPending(w)){const d=workDuration(w,state);if(d.hours===null)row.unknownHours++;else row.remainingHours+=d.hours;}types.set(w.type,row);}return [...types.values()];}
export function weeklyLoad(state,start){const from=new Date(start+'T00:00:00'),rows=Array.from({length:7},(_,i)=>{const d=new Date(from);d.setDate(d.getDate()+i);return{date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,hours:0,unknown:0,works:[]};});for(const w of active(state,'interventions').filter(w=>isPending(w))){const row=rows.find(r=>r.date===String(w.plannedDate||w.date).slice(0,10));if(row){const estimate=workDuration(w,state);row.works.push(w);if(estimate.hours===null)row.unknown++;else row.hours+=estimate.hours;}}return rows;}
function center(p){const c=p?.geometry?geometryCentroid(p.geometry):null;return c;}
export function proposePlan(state,works,{date,startHour=8,speed=20,weather=null,origin=null}={}){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(startHour)||startHour<0||startHour>=24||!(speed>0&&speed<=100))throw Error('Paramètres de planning invalides.');
  const items=works.filter(w=>isPending(w)).map(w=>({work:w,point:center(active(state,'parcelles').find(p=>p.id===w.parcelId)),estimate:workDuration(w,state)}));const todo=[...items],ordered=[];let position=origin,estimatedHour=startHour;const windows=new Map();for(const item of items){const kind=['Semis','Fauche','Pulvérisation','Fertilisation','Récolte','Épandage'].find(t=>normalize(item.work.type).includes(normalize(t)));if(kind&&!windows.has(kind))windows.set(kind,weatherWindows(weather,kind).windows);item.kind=kind;}const constraintRank=item=>{const stamp=new Date(date+'T00:00:00').getTime()+estimatedHour*3600000,level=windows.get(item.kind)?.find(w=>stamp>=w.start&&stamp<w.end)?.level;const overdue=String(item.work.plannedDate||item.work.date||'').slice(0,10);return (level==='unfavorable'?100:0)+(item.work.priority==='Haute'?-30:0)+(overdue&&overdue<date?-20:0)+(position&&item.point?haversineMeters(position,item.point)/1000:10);};
  while(todo.length){let pick=todo.reduce((best,x,i)=>constraintRank(x)<constraintRank(todo[best])?i:best,0);const item=todo.splice(pick,1)[0];ordered.push(item);estimatedHour+=item.estimate.hours||0;position=item.point;}
  const route=list=>{let total=0,last=origin,unknown=0;for(const item of list){if(last&&item.point)total+=haversineMeters(last,item.point)/1000;else if(last||item!==list[0])unknown++;last=item.point;}return{km:total,unknown};};
  let hour=startHour,previous=origin;const rows=ordered.map(item=>{const travel=previous&&item.point?haversineMeters(previous,item.point)/1000/speed:null;if(travel!==null&&hour!==null)hour+=travel;const start=hour,end=start!==null&&item.estimate.hours!==null?start+item.estimate.hours:null;hour=end;previous=item.point;
    const reasons=[...(item.work.priority==='Haute'?['Priorité haute saisie']:[]),...(String(item.work.plannedDate||item.work.date||'')<date?['Échéance antérieure au jour proposé']:[]),`${item.estimate.confidence}${item.estimate.samples?' · '+item.estimate.samples+' références':''}`,item.point?'Ordre de proximité à vol d’oiseau':'Localisation manquante'];
    const machine=active(state,'materiels').find(m=>m.id===item.work.equipmentId);if(machine?.maintenanceDue!==null&&machine?.currentMeter!==null&&machine?.maintenanceDue<=machine?.currentMeter)reasons.push('Entretien matériel à vérifier');
    if(item.work.product){const stock=active(state,'stockItems').find(s=>normalize(s.name)===normalize(item.work.product));reasons.push(stock?`Stock observé : ${stock.quantity} ${stock.unit||''} (besoin à vérifier)`:'Stock non renseigné');}
    const kind=Object.keys({Semis:1,Fauche:1,Pulvérisation:1,Fertilisation:1,Récolte:1,Épandage:1}).find(t=>normalize(item.work.type).includes(normalize(t)));
    if(weather&&kind&&start!==null){const stamp=new Date(date+'T00:00:00').getTime()+start*3600000;const window=weatherWindows(weather,kind).windows.find(w=>stamp>=w.start&&stamp<w.end);reasons.push(window?`Météo : ${window.level}`:'Prévision indisponible à cet horaire');}
    for(const other of active(state,'interventions').filter(w=>isPending(w)&&!works.some(x=>x.id===w.id)&&String(w.plannedDate||w.date).slice(0,10)===date)){if((other.equipmentId&&other.equipmentId===item.work.equipmentId)||(other.operator&&other.operator===item.work.operator))reasons.push('Autre travail ce jour pour le matériel ou l’opérateur : disponibilité à valider');}
    return{...item,start,end,reasons};});return{date,rows,route:route(ordered),originalRoute:route(items),speed,confidence:rows.every(r=>r.end!==null)?'Proposition à valider':'Données insuffisantes pour tous les horaires'};
}
export function groupingOpportunity(state){const pending=active(state,'interventions').filter(w=>isPending(w)).slice(0,100),parcels=new Map(active(state,'parcelles').map(p=>[p.id,p]));for(let i=0;i<pending.length;i++)for(let j=i+1;j<pending.length;j++){const a=pending[i],b=pending[j];if(a.parcelId===b.parcelId||a.type!==b.type||!a.equipmentId||a.equipmentId!==b.equipmentId||(a.plannedDate||a.date)!==(b.plannedDate||b.date))continue;const pa=parcels.get(a.parcelId),pb=parcels.get(b.parcelId),ca=center(pa),cb=center(pb);if(ca&&cb){const meters=haversineMeters(ca,cb);if(meters<=2000)return{workIds:[a.id,b.id],text:`Regrouper ${pa.nom} et ${pb.nom} : ${a.type}, même matériel, centres distants d’environ ${(meters/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})} km à vol d’oiseau. Itinéraire et disponibilités à vérifier.`};}}return null;}
// Greedy, explainable schedule with explicit resource intervals, occupied slots and stock budgets.
export function proposeConstrainedPlan(state,works,{date,startHour=8,endHour=18,speed=20,weather=null,origin=null,availability={},requireWeather=false,checkMaintenance=true}={}){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(startHour)||!Number.isFinite(endHour)||startHour<0||endHour>24||startHour>=endHour||!(speed>0&&speed<=100))throw Error('Journée ou vitesse invalide.');
 const parcels=new Map(active(state,'parcelles').map(p=>[p.id,p])),machines=new Map(active(state,'materiels').map(m=>[m.id,m])),stock=new Map(active(state,'stockItems').map(s=>[s.id,{...s,remaining:s.quantity}])),selected=new Set(works.map(w=>w.id)),bookings=[];const time=value=>/^\d{2}:\d{2}$/.test(value||'')?Number(value.slice(0,2))+Number(value.slice(3))/60:null;
 for(const w of active(state,'interventions').filter(w=>isPending(w)&&!selected.has(w.id)&&String(w.plannedDate||w.date).slice(0,10)===date)){const start=time(w.startTime),duration=workDuration(w,state).hours,end=time(w.endTime);bookings.push({machine:w.equipmentId,operator:w.operator,start:start??0,end:start!==null&&end!==null&&end>start?end:start!==null&&duration!==null?start+duration:24});}
 const pending=works.filter(w=>isPending(w)).map(work=>({work,point:center(parcels.get(work.parcelId)),estimate:workDuration(work,state)})),rows=[],unscheduled=[],usedHours=new Map(),windows=new Map();let cursor=startHour,position=origin,totalKm=0,totalTravel=0,unknownSegments=0;
 const evaluate=item=>{const {work:w,estimate}=item,why=[],warnings=[],machine=machines.get(w.equipmentId),travel=position&&item.point?haversineMeters(position,item.point)/1000/speed:0,keys=[w.equipmentId?'machine:'+w.equipmentId:null,w.operator?'operator:'+w.operator:null].filter(Boolean);if(estimate.hours===null)return{reason:'Durée inconnue'};if(!w.equipmentId||!machine)warnings.push('Matériel non attribué ou introuvable');if(checkMaintenance&&machine&&(number(machine.maintenanceDue)===null||number(machine.currentMeter)===null))warnings.push('Échéance ou compteur matériel inconnu');if(!w.operator)warnings.push('Opérateur non attribué');if(!item.point||!position)warnings.push('Trajet initial ou position manquante ; temps non chiffré');if(checkMaintenance&&machine&&number(machine.maintenanceDue)!==null&&number(machine.currentMeter)!==null&&machine.currentMeter+(usedHours.get(machine.id)||0)+estimate.hours>machine.maintenanceDue)return{reason:'Entretien à prévoir avant ces heures de travail'};
 let input=null,quantity=null;if(w.product){const matches=[...stock.values()].filter(s=>normalize(s.name)===normalize(w.product));input=w.stockItemId?stock.get(w.stockItemId):matches.length===1?matches[0]:null;if(input){quantity=stockRequirement(w,input);if(quantity===null||!Number.isFinite(input.remaining))warnings.push('Unité ou quantité stock non vérifiable');else if(quantity>input.remaining+1e-9)return{reason:'Stock insuffisant après les chantiers précédents'};}else warnings.push('Produit sans stock associé univoque');}
 const kind=['Semis','Fauche','Pulvérisation','Fertilisation','Récolte','Épandage'].find(t=>normalize(w.type).includes(normalize(t)));if(kind&&!windows.has(kind))windows.set(kind,weatherWindows(weather,kind,{rules:{...WEATHER_RULES[kind],...(state.preferences?.decisionWeatherRules?.[kind]||{})}}).windows);const forecast=windows.get(kind)||[];
 for(let start=Math.ceil((cursor+travel)*4)/4;start+estimate.hours<=endHour+1e-9;start+=.25){const end=start+estimate.hours;if(keys.some(key=>{const slots=availability[key];return slots&&!slots.some(r=>start-travel>=r.start&&end<=r.end);}))continue;if(bookings.some(b=>((w.equipmentId&&b.machine===w.equipmentId)||(w.operator&&b.operator===w.operator))&&start-travel<b.end&&end>b.start))continue;let bad=false,unknown=false;for(let t=start;t<end;t+=.25){const stamp=new Date(date+'T00:00:00').getTime()+t*3600000,window=forecast.find(f=>stamp>=f.start&&stamp<f.end);if(window?.level==='unfavorable')bad=true;if(!window||window.level==='unknown')unknown=true;}if(bad||requireWeather&&unknown)continue;why.push(estimate.confidence,'Aucun conflit sur les créneaux connus');if(keys.some(k=>!availability[k]))warnings.push('Disponibilité non renseignée, plage de journée supposée');if(unknown)warnings.push('Météo incomplète sur le chantier');else why.push('Météo vérifiée sur la durée proposée');if(input&&quantity!==null&&Number.isFinite(input.remaining))why.push(`Besoin ${quantity.toFixed(2)} ${input.unit}, stock restant ${input.remaining.toFixed(2)}`);if(w.priority==='Haute')why.push('Priorité haute saisie');return{start,end,travel,km:travel*speed,input,quantity,reasons:[...why,...warnings],warnings};}return{reason:'Aucun créneau compatible (disponibilité, météo, autres travaux ou fin de journée)'};};
 while(pending.length){const candidates=pending.map((item,index)=>({item,index,result:evaluate(item)})).filter(x=>!x.result.reason);if(!candidates.length){for(const item of pending)unscheduled.push({work:item.work,reason:evaluate(item).reason});break;}candidates.sort((a,b)=>{const rank=x=>x.result.start+(x.item.work.priority==='Haute'?-1:0)+(String(x.item.work.plannedDate||x.item.work.date||date)<date?-.5:0);return rank(a)-rank(b)||a.result.km-b.result.km;});const chosen=candidates[0],{item,result}=chosen;pending.splice(chosen.index,1);rows.push({...item,...result});cursor=result.end;totalKm+=result.km;totalTravel+=result.travel;if(!position||!item.point)unknownSegments++;position=item.point;if(result.input&&result.quantity!==null)result.input.remaining-=result.quantity;if(item.work.equipmentId)usedHours.set(item.work.equipmentId,(usedHours.get(item.work.equipmentId)||0)+item.estimate.hours);bookings.push({machine:item.work.equipmentId,operator:item.work.operator,start:result.start,end:result.end});}
 let originalKm=0,last=origin,originalUnknown=0;for(const w of works){const p=center(parcels.get(w.parcelId));if(last&&p)originalKm+=haversineMeters(last,p)/1000;else originalUnknown++;last=p;}return{date,rows,unscheduled,route:{km:totalKm,unknown:unknownSegments},originalRoute:{km:originalKm,unknown:originalUnknown},travelHours:totalTravel,speed,confidence:rows.some(r=>r.warnings.length)?'Proposition avec hypothèses à confirmer':unscheduled.length?'Proposition partielle':'Contraintes renseignées respectées',availability,requireWeather,checkMaintenance};
}
