import {active,completed,parcelMemory} from './farm-memory.js';import {normalize,campaignFor} from './utils.js';import {isPending,agendaDate,localDay} from './home-priorities.js';
const open=(section,label,extra={})=>({type:'open_farm',label,payload:{section,...extra}});
export function answerFarmQuestion(question,state,context={}){const q=normalize(question),works=active(state,'interventions'),parcels=active(state,'parcelles'),named=parcels.find(p=>normalize(p.nom)&&q.includes(normalize(p.nom)))||parcels.find(p=>p.id===context.currentParcelId);const reply=(intent,answer,actions=[])=>({recognized:true,intent,answer,actions});
 if(/organis|prepare|planifi/.test(q)&&/demain|semis|travaux|planning/.test(q)){const type=/semis|semer/.test(q)?'Semis':null,list=works.filter(w=>isPending(w)&&(!type||/sem/.test(normalize(w.type)))),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);return reply('supervised_plan',`${list.length} travaux${type?' de semis':''} en attente. Je peux préparer un ordre de proximité et estimer les durées connues. Météo, matériel, stocks et disponibilités seront présentés pour vérification. Aucune date ne sera modifiée avant votre validation.`,[open('plan','Préparer le plan',{date:/demain/.test(q)?localDay(tomorrow):localDay(),type})]);}
 if(/pourquoi/.test(q)&&/priorit|parcelle/.test(q)&&named){const rows=works.filter(w=>w.parcelId===named.id&&isPending(w)),overdue=rows.filter(w=>agendaDate(w)&&agendaDate(w)<localDay()),obs=active(state,'observations').filter(o=>o.parcelId===named.id&&o.status!=='Résolu');return reply('explain_priority',`${named.nom} : ${overdue.length} travaux datés en retard, ${rows.length} travaux en attente, ${obs.length} observations ouvertes. Ce sont les faits disponibles ; disponibilité matériel, stock requis et météo locale ne sont pas supposés.`,[open('observations','Vérifier la situation',{parcelId:named.id})]);}
 if(/parcelle/.test(q)&&/aller voir|visiter|surveiller/.test(q)){const signals=context.farmSignals||[],obs=active(state,'observations').filter(o=>o.status!=='Résolu'),ids=[...new Set([...signals.map(s=>s.parcelId),...obs.map(o=>o.parcelId)])].slice(0,3);return reply('visit_parcels',ids.length?`À vérifier : ${ids.map(id=>{const p=parcels.find(p=>p.id===id),s=signals.find(s=>s.parcelId===id);return `${p?.nom||'Parcelle'} — ${s?s.title+' (image du '+s.date+')':'observation ouverte'}`;}).join(' ; ')}. Ce sont des signaux, pas des diagnostics.`:'Aucune observation ouverte ni anomalie satellite consultée à signaler. Les parcelles sans données ne sont pas considérées comme vérifiées.',ids.map(id=>open('observations','Voir '+(parcels.find(p=>p.id===id)?.nom||'parcelle'),{parcelId:id})));}
 if(/compar/.test(q)&&/20\d\d/.test(q)){const years=[...new Set(q.match(/20\d\d/g)||[])];if(named&&years.length>=2){const results=years.slice(0,2).map(y=>parcelMemory(state,named.id,`${y}/${String(Number(y)+1).slice(-2)}`));return reply('compare_campaign',results.map(r=>`Campagne ${r.campaign} : ${r.culture||'culture inconnue'}, ${r.works} interventions réalisées, ${r.knownCost.toFixed(2)} € de coûts saisis${r.missingCost?' (incomplets)':''}`).join('\n'),[open('memory','Ouvrir la comparaison',{parcelId:named.id})]);}return reply('compare_campaign','Choisissez une parcelle et deux campagnes pour comparer des faits datés.',[open('memory','Comparer les campagnes')]);}
 if(/cout|cher/.test(q)&&/trav|intervention/.test(q)){const list=works.filter(w=>completed(w)&&typeof w.cost==='number'&&Number.isFinite(w.cost)).sort((a,b)=>b.cost-a.cost).slice(0,5);return reply('expensive_works',list.length?list.map(w=>`${w.type} — ${parcels.find(p=>p.id===w.parcelId)?.nom||'Parcelle'} : ${w.cost.toFixed(2)} € saisis`).join('\n'):'Aucun coût réalisé chiffré disponible.',list.map(w=>({type:'open_work',label:'Voir '+w.type,payload:{workId:w.id}})));}
 if(/rendement|fertilis/.test(q)&&/perdu|repond|mieux|effet|resultat/.test(q))return reply('outcome_correlation','Les relevés de rendement et les évolutions NDVI permettent des comparaisons, pas une attribution certaine à la fertilisation. Consultez les données avant/après et les zones mesurées ; aucune perte ni gain n’est inventé sans référence comparable.',[open('results','Comparer avant / après',{parcelId:named?.id}),open('zones','Examiner les rendements',{parcelId:named?.id})]);
 return null;
}
