import {campaignFor,geometryCentroid,haversineMeters,normalize} from './utils.js';
import {active,completed} from './farm-memory.js';
import {isPending} from './home-priorities.js';
import {weatherWindows} from './weather-decision.js';
const number=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
export function workDuration(work,state){if(number(work.duration)!==null&&work.duration>0)return{hours:work.duration,confidence:'Durée saisie',samples:0};const p=active(state,'parcelles').find(p=>p.id===work.parcelId),area=number(work.surfaceWorked)??number(p?.surfaceHa);const history=active(state,'interventions').filter(w=>completed(w)&&normalize(w.type)===normalize(work.type)&&w.duration>0&&w.surfaceWorked>0&&(!work.equipmentId||w.equipmentId===work.equipmentId)).map(w=>w.duration/w.surfaceWorked).sort((a,b)=>a-b);return{hours:area>0&&history.length?area*history[Math.floor(history.length/2)]:null,confidence:history.length>=3?'Estimation historique':'Données insuffisantes',samples:history.length};}
export function campaignProgress(state,campaign){const types=new Map();for(const w of active(state,'interventions').filter(w=>w.status!=='Annulé'&&(w.campaignId||((w.plannedDate||w.date)?campaignFor(w.plannedDate||w.date):null))===campaign)){const p=active(state,'parcelles').find(p=>p.id===w.parcelId),area=number(w.surfaceWorked)??number(p?.surfaceHa),row=types.get(w.type)||{type:w.type,planned:0,done:0,missingArea:0,remainingHours:0,unknownHours:0};if(area===null)row.missingArea++;else{row.planned+=area;if(completed(w))row.done+=area;}if(isPending(w)){const d=workDuration(w,state);if(d.hours===null)row.unknownHours++;else row.remainingHours+=d.hours;}types.set(w.type,row);}return [...types.values()];}
export function weeklyLoad(state,start){const from=new Date(start+'T00:00:00'),rows=Array.from({length:7},(_,i)=>{const d=new Date(from);d.setDate(d.getDate()+i);return{date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,hours:0,unknown:0,works:[]};});for(const w of active(state,'interventions').filter(w=>isPending(w))){const row=rows.find(r=>r.date===String(w.plannedDate||w.date).slice(0,10));if(row){const estimate=workDuration(w,state);row.works.push(w);if(estimate.hours===null)row.unknown++;else row.hours+=estimate.hours;}}return rows;}
function center(p){const c=p?.geometry?geometryCentroid(p.geometry):null;return c;}
export function proposePlan(state,works,{date,startHour=8,speed=20,weather=null,origin=null}={}){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(startHour)||startHour<0||startHour>=24||!(speed>0&&speed<=100))throw Error('Paramètres de planning invalides.');
  const items=works.filter(w=>isPending(w)).map(w=>({work:w,point:center(active(state,'parcelles').find(p=>p.id===w.parcelId)),estimate:workDuration(w,state)}));const todo=[...items],ordered=[];let position=origin,estimatedHour=startHour;const windows=new Map();for(const item of items){const kind=['Semis','Fauche','Pulvérisation','Fertilisation','Récolte','Épandage'].find(t=>normalize(item.work.type).includes(normalize(t)));if(kind&&!windows.has(kind))windows.set(kind,weatherWindows(weather,kind).windows);item.kind=kind;}const constraintRank=item=>{const stamp=new Date(date+'T00:00:00').getTime()+estimatedHour*3600000,level=windows.get(item.kind)?.find(w=>stamp>=w.start&&stamp<w.end)?.level;const overdue=String(item.work.plannedDate||item.work.date||'').slice(0,10);return (level==='unfavorable'?100:0)+(item.work.priority==='Haute'?-30:0)+(overdue&&overdue<date?-20:0)+(position&&item.point?haversineMeters(position,item.point)/1000:10);};
  while(todo.length){let pick=todo.reduce((best,x,i)=>constraintRank(x)<constraintRank(todo[best])?i:best,0);const item=todo.splice(pick,1)[0];ordered.push(item);estimatedHour+=item.estimate.hours||0;position=item.point||position;}
  const route=list=>{let total=0,last=origin,unknown=0;for(const item of list){if(last&&item.point)total+=haversineMeters(last,item.point)/1000;else if(last||item!==list[0])unknown++;last=item.point;}return{km:total,unknown};};
  let hour=startHour,previous=origin;const rows=ordered.map(item=>{const travel=previous&&item.point?haversineMeters(previous,item.point)/1000/speed:null;if(travel!==null&&hour!==null)hour+=travel;const start=hour,end=start!==null&&item.estimate.hours!==null?start+item.estimate.hours:null;hour=end;previous=item.point;
    const reasons=[...(item.work.priority==='Haute'?['Priorité haute saisie']:[]),...(String(item.work.plannedDate||item.work.date||'')<date?['Échéance antérieure au jour proposé']:[]),`${item.estimate.confidence}${item.estimate.samples?' · '+item.estimate.samples+' références':''}`,item.point?'Ordre de proximité à vol d’oiseau':'Localisation manquante'];
    const machine=active(state,'materiels').find(m=>m.id===item.work.equipmentId);if(machine?.maintenanceDue!==null&&machine?.currentMeter!==null&&machine?.maintenanceDue<=machine?.currentMeter)reasons.push('Entretien matériel à vérifier');
    if(item.work.product){const stock=active(state,'stockItems').find(s=>normalize(s.name)===normalize(item.work.product));reasons.push(stock?`Stock observé : ${stock.quantity} ${stock.unit||''} (besoin à vérifier)`:'Stock non renseigné');}
    const kind=Object.keys({Semis:1,Fauche:1,Pulvérisation:1,Fertilisation:1,Récolte:1,Épandage:1}).find(t=>normalize(item.work.type).includes(normalize(t)));
    if(weather&&kind&&start!==null){const stamp=new Date(date+'T00:00:00').getTime()+start*3600000;const window=weatherWindows(weather,kind).windows.find(w=>stamp>=w.start&&stamp<w.end);reasons.push(window?`Météo : ${window.level}`:'Prévision indisponible à cet horaire');}
    for(const other of active(state,'interventions').filter(w=>isPending(w)&&!works.some(x=>x.id===w.id)&&String(w.plannedDate||w.date).slice(0,10)===date)){if((other.equipmentId&&other.equipmentId===item.work.equipmentId)||(other.operator&&other.operator===item.work.operator))reasons.push('Autre travail ce jour pour le matériel ou l’opérateur : disponibilité à valider');}
    return{...item,start,end,reasons};});return{date,rows,route:route(ordered),originalRoute:route(items),speed,confidence:rows.every(r=>r.end!==null)?'Proposition à valider':'Données insuffisantes pour tous les horaires'};
}
export function groupingOpportunity(state){const pending=active(state,'interventions').filter(w=>isPending(w)).slice(0,100),parcels=new Map(active(state,'parcelles').map(p=>[p.id,p]));for(let i=0;i<pending.length;i++)for(let j=i+1;j<pending.length;j++){const a=pending[i],b=pending[j];if(a.parcelId===b.parcelId||a.type!==b.type||!a.equipmentId||a.equipmentId!==b.equipmentId||(a.plannedDate||a.date)!==(b.plannedDate||b.date))continue;const pa=parcels.get(a.parcelId),pb=parcels.get(b.parcelId),ca=center(pa),cb=center(pb);if(ca&&cb){const meters=haversineMeters(ca,cb);if(meters<=2000)return{workIds:[a.id,b.id],text:`Regrouper ${pa.nom} et ${pb.nom} : ${a.type}, même matériel, centres distants d’environ ${(meters/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})} km à vol d’oiseau. Itinéraire et disponibilités à vérifier.`};}}return null;}
