import {validateForm} from './form-chips-ui.js';import {escapeHtml as e,downloadBlob,uid} from './utils.js';import {farmRecords,saveFarmRecord} from './farm-records.js';import {harvestTrace,parcelFollowupScore} from './harvest-traceability.js';import {active} from './farm-memory.js';import {contractsForLot,contractTypeLabel} from './sales.js';
export async function harvestAction(action,control,c){if(!['harvest','harvest-save','harvest-open','harvest-sale','harvest-sale-save','parcel-score','share-parcel'].includes(action))return false;const{host,show,button,fmt,data,parcel}=c,p=parcel();if(!p)throw Error('Parcelle nécessaire.');const lots=()=>farmRecords(data(),'harvest').filter(l=>l.parcelId===p.id);
 if(action==='harvest'){show('Lots de récolte · '+p.nom,`${lots().map(l=>`<p>${e(l.code)} · ${fmt(l.quantity)} ${e(l.unit)} ${button('harvest-open','Tracer le lot',`data-id="${e(l.id)}"`)}</p>`).join('')}<details><summary>Nouveau lot</summary><form id="harvest-form" class="form-grid"><label>Code lot<input name="code" required></label><label>Date récolte<input name="date" type="date" required></label><label>Culture<input name="crop" value="${e(p.culture||'')}"></label><label>Quantité<input name="quantity" type="number" min="0" step="any" required></label><label>Unité<select name="unit"><option>t</option><option>kg</option></select></label><label>Humidité (%)<input name="humidity" type="number" min="0" max="100" step="any"></label><label>Silo / stockage<input name="silo"></label></form>${button('harvest-save','Valider le lot')}</details><p>Aucune entrée de stock n’est créée automatiquement.</p>`);}
 else if(action==='harvest-save'){const f=document.querySelector('#harvest-form');if(!validateForm(f))return;const v=Object.fromEntries(new FormData(f));v.quantity=Number(v.quantity);v.humidity=v.humidity===''?null:Number(v.humidity);if(farmRecords(data(),'harvest').some(l=>l.code===v.code))throw Error('Ce code lot existe déjà.');await saveFarmRecord(host.store,'harvest',{...v,name:v.code,parcelId:p.id,sales:[]});await harvestAction('harvest',control,c);}
 else if(action==='harvest-open'){const lot=lots().find(l=>l.id===control.dataset.id);if(!lot)throw Error('Lot introuvable.');const trace=harvestTrace(data(),lot);show('Traçabilité · '+lot.code,`<p>${e(p.nom)} → ${e(trace.culture||'Culture inconnue')} → récolte du ${e(lot.date)} → ${e(lot.silo||'Stockage non renseigné')}</p><p>${fmt(lot.quantity)} ${e(lot.unit)} · humidité ${fmt(lot.humidity)} %</p><h3>Interventions de la campagne</h3>${trace.works.map(w=>`<p>${e(w.date)} · ${e(w.type)} · ${e(w.product||'')} ${e(w.dose??'')} ${e(w.doseUnit||'')} · ${e(w.operator||'opérateur inconnu')} · ${e(active(data(),'materiels').find(m=>m.id===w.equipmentId)?.nom||'matériel inconnu')}</p>`).join('')}<p>${trace.documents.length} documents associés. Liens déduits de la parcelle et de la campagne, pas une preuve d’appartenance de chaque intrant au lot.</p><h3>Ventes / sorties déclarées</h3>${trace.sales.map(s=>{const k=s.contractId?contractsForLot(data(),lot).find(x=>x.id===s.contractId):null;return`<p>${e(s.date)} · ${e(s.buyer)} · ${fmt(s.quantity)} ${e(lot.unit)}${k?` · contrat ${e(k.buyer)}`:''}</p>`;}).join('')}`,button('harvest-sale','Ajouter une vente déclarée',`data-id="${e(lot.id)}"`));}
 else if(action==='harvest-sale'){const saleLot=lots().find(l=>l.id===control.dataset.id),saleContracts=saleLot?contractsForLot(data(),saleLot):[];show('Vente du lot',`<form id="harvest-sale-form" data-id="${e(control.dataset.id)}" class="form-grid"><label>Date<input name="date" type="date" required></label><label>Acheteur<input name="buyer" required></label><label>Quantité (unité du lot)<input name="quantity" type="number" min="0" step="any" required></label><label>Prix unitaire<input name="price" type="number" min="0" step="any"></label>${saleContracts.length?`<label>Contrat (facultatif)<select name="contractId"><option value="">Aucun contrat</option>${saleContracts.map(k=>`<option value="${e(k.id)}">${e(k.buyer)} · ${e(contractTypeLabel(k.type))} · ${e(k.tonnes)} t</option>`).join('')}</select></label>`:''}</form><p>Déclaration de traçabilité ; les stocks et factures ne sont pas modifiés.</p>`,button('harvest-sale-save','Valider cette vente'));}
 else if(action==='harvest-sale-save'){const f=document.querySelector('#harvest-sale-form');if(!validateForm(f))return;const lot=lots().find(l=>l.id===f.dataset.id),v=Object.fromEntries(new FormData(f));v.quantity=Number(v.quantity);v.price=v.price===''?null:Number(v.price);if(!v.contractId)delete v.contractId;if(!lot||v.quantity+(lot.sales||[]).reduce((s,r)=>s+r.quantity,0)>lot.quantity)throw Error('Quantité supérieure au solde du lot.');await saveFarmRecord(host.store,'harvest',{...lot,sales:[...(lot.sales||[]),{...v,id:uid('sale')}]},lot);await harvestAction('harvest-open',{dataset:{id:lot.id}},c);}
 else if(action==='parcel-score'){const score=parcelFollowupScore(data(),p);show('Score de suivi · '+p.nom,score?`<h2>${score.score} / 100</h2><p>${score.label}</p><details open><summary>Voir le calcul</summary>${score.criteria.map(r=>`<p>${e(r.label)} : ${r.known}/${r.total} · poids 25 %</p>`).join('')}<p>Moyenne des quatre taux de complétude. Aucun point n’est attribué à un potentiel agronomique non mesuré.</p></details>`:'<p>Données insuffisantes : aucun travail réalisé.</p>');}
 else if(action==='share-parcel'){const text=[p.nom,`${p.surfaceHa??'Surface inconnue'} ha`,p.culture||'',p.commune||''].filter(Boolean).join('\n'),file=new File([JSON.stringify({type:'Feature',geometry:p.geometry||null,properties:{name:p.nom,surfaceHa:p.surfaceHa,culture:p.culture}},null,2)],'parcelle.geojson',{type:'application/geo+json'});if(navigator.canShare?.({files:[file]}))await navigator.share({title:p.nom,text,files:[file]});else downloadBlob('parcelle.geojson',file);}
 return true;
}
