// ESRI Shapefile technical description: polygon records + matching SHX/DBF.
import {geometryAreaHa} from './utils.js';
import {createZip} from './zip-lite.js';
import {prescriptionGeoJson} from './prescriptions.js';
export const WGS84_PRJ='GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]]';
const bounds=points=>[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];
function header(view,length,box){view.setInt32(0,9994);view.setInt32(24,length/2);view.setInt32(28,1000,true);view.setInt32(32,5,true);box.forEach((v,i)=>view.setFloat64(36+i*8,v,true));}
// Écriture SHP/SHX/DBF générique (polygones, WGS 84, DBF UTF-8). items : [{geometry, values}], fields : [[NOM,type,taille,décimales]].
// truncate : les textes trop longs sont coupés (sans casser un caractère) au lieu de lever une erreur.
export function polygonShapefile(items,fields,{truncate=false,invalidMessage='Valeur invalide.'}={}){const enc=new TextEncoder();const records=items.map(item=>{const g=item.geometry,polygons=g?.type==='Polygon'?[g.coordinates]:g?.type==='MultiPolygon'?g.coordinates:null;if(!polygons)throw Error('Polygones requis.');const rings=polygons.flatMap(poly=>poly.map((r,i)=>{if(r.length<4||r.some(p=>p.length<2||p.some(v=>!Number.isFinite(v))))throw Error('Contour invalide.');const signed=r.slice(1).reduce((s,p,j)=>s+r[j][0]*p[1]-p[0]*r[j][1],0);return(signed>0)===(i===0)?[...r].reverse():r;}));const points=rings.flat(),data=new ArrayBuffer(44+rings.length*4+points.length*16),v=new DataView(data);v.setInt32(0,5,true);bounds(points).forEach((x,i)=>v.setFloat64(4+8*i,x,true));v.setInt32(36,rings.length,true);v.setInt32(40,points.length,true);let start=0;rings.forEach((r,i)=>{v.setInt32(44+4*i,start,true);start+=r.length;});points.forEach((p,i)=>{v.setFloat64(44+rings.length*4+i*16,p[0],true);v.setFloat64(52+rings.length*4+i*16,p[1],true);});return{data,box:bounds(points)};});
 const box=[Math.min(...records.map(r=>r.box[0])),Math.min(...records.map(r=>r.box[1])),Math.max(...records.map(r=>r.box[2])),Math.max(...records.map(r=>r.box[3]))],shp=new ArrayBuffer(100+records.reduce((s,r)=>s+r.data.byteLength+8,0)),shx=new ArrayBuffer(100+records.length*8),sv=new DataView(shp),xv=new DataView(shx);header(sv,shp.byteLength,box);header(xv,shx.byteLength,box);let offset=100;records.forEach((r,i)=>{sv.setInt32(offset,i+1);sv.setInt32(offset+4,r.data.byteLength/2);new Uint8Array(shp,offset+8,r.data.byteLength).set(new Uint8Array(r.data));xv.setInt32(100+i*8,offset/2);xv.setInt32(104+i*8,r.data.byteLength/2);offset+=8+r.data.byteLength;});
 const fit=(text,size)=>{let out='';for(const ch of text){if(enc.encode(out+ch).length>size)break;out+=ch;}return out;};
 const headerLength=33+32*fields.length,rowLength=1+fields.reduce((s,f)=>s+f[2],0),dbf=new Uint8Array(headerLength+rowLength*items.length+1),dv=new DataView(dbf.buffer),date=new Date();dbf[0]=3;dbf[1]=date.getUTCFullYear()-1900;dbf[2]=date.getUTCMonth()+1;dbf[3]=date.getUTCDate();dv.setUint32(4,items.length,true);dv.setUint16(8,headerLength,true);dv.setUint16(10,rowLength,true);fields.forEach(([name,type,size,decimal],i)=>{const o=32+i*32;dbf.set(enc.encode(name),o);dbf[o+11]=type.charCodeAt(0);dbf[o+16]=size;dbf[o+17]=decimal;});dbf[headerLength-1]=13;items.forEach((item,i)=>{let o=headerLength+i*rowLength;dbf[o++]=32;item.values.forEach((value,j)=>{const [,type,size,decimals]=fields[j];if(type==='N'&&(!Number.isFinite(value)||value<0))throw Error(invalidMessage);let text=type==='N'?value.toFixed(decimals):String(value??'');if(enc.encode(text).length>size){if(truncate&&type!=='N')text=fit(text,size);else throw Error('Valeur trop grande pour le format SHP.');}dbf.set(enc.encode(type==='N'?text.padStart(size):text),o);dbf.fill(32,o+enc.encode(type==='N'?text.padStart(size):text).length,o+size);o+=size;});});dbf[dbf.length-1]=26;return{shp,shx,dbf:dbf.buffer,prj:WGS84_PRJ,cpg:'UTF-8'};
}
export function prescriptionShapefile(zones,plan){const features=prescriptionGeoJson(zones,plan).features;if(!features.length||features.length>2500)throw Error('1 à 2 500 cellules nécessaires.');if(features.some(f=>f.geometry.type!=='Polygon'))throw Error('Polygones requis.');
 return polygonShapefile(features.map(f=>({geometry:f.geometry,values:[f.properties.zone,f.properties.rate,f.properties.unit,f.properties.area_ha]})),[['ZONE','C',8,0],['RATE','N',18,6],['UNIT','C',16,0],['AREA_HA','N',18,8]],{invalidMessage:'Valeur de prescription invalide.'});
}
export async function shapefileZip(zones,plan){const files=prescriptionShapefile(zones,plan);return createZip(Object.entries(files).map(([ext,data])=>({name:'prescription.'+ext,data:new Blob([data])})));}
// ISO 11783-10 v4.3 grid type 1; DDI factors from the ISOBUS data dictionary.
// Zero-rate zone is explicit for unmeasured/disabled cells and lost GPS position.
export function prescriptionIsoxml(zones,plan){const geometry=JSON.parse(zones.geometrySignature),polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:null;if(!polygons)throw Error('Contour polygonal requis.');const box=bounds(polygons.flat(2)),dy=zones.cellMeters/111320,dx=dy/Math.cos((box[1]+box[3])/2*Math.PI/180),columns=Math.ceil((box[2]-box[0])/dx),rows=Math.ceil((box[3]-box[1])/dy);if(!(columns>0&&rows>0&&columns*rows<=2500))throw Error('Grille ISOXML trop grande ou invalide.');const spec={'kg/ha':['0006',100,.01],'L/ha':['0001',10000,.0001],'graines/ha':['000B',.1,10]}[plan.unit];if(!spec)throw Error('Unité ISOXML non prise en charge.');const [ddi,factor,scale]=spec,grid=new Uint8Array(columns*rows),groups=[...new Set(zones.cells.filter(c=>c.enabled).map(c=>c.group))];if(!groups.length||groups.length>253)throw Error('Nombre de zones invalide.');const codes=new Map(groups.map((g,i)=>[g,i+1])),raw=rate=>{const n=Math.round(rate*factor);if(!Number.isFinite(rate)||rate<0||n>2147483647||Math.abs(n/factor-rate)>1e-6)throw Error('Dose non représentable exactement dans cette unité ISOXML.');return n;};for(const cell of zones.cells.filter(c=>c.enabled)){const [i,j]=cell.id.split(':').map(Number),ring=cell.geometry.coordinates[0];if(!Number.isInteger(i)||!Number.isInteger(j)||i<0||j<0||i>=columns||j>=rows||Math.abs(ring[0][0]-(box[0]+i*dx))>1e-9||Math.abs(ring[0][1]-(box[1]+j*dy))>1e-9)throw Error('Cellule non alignée sur la grille ISOXML.');grid[j*columns+i]=codes.get(cell.group);}
 const xmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])),boundary=polygons.map(poly=>`<PLN A="1">${poly.map((ring,i)=>`<LSG A="${i===0?1:2}">${ring.map(([lon,lat])=>`<PNT A="2" C="${lat.toFixed(10)}" D="${lon.toFixed(10)}"/>`).join('')}</LSG>`).join('')}</PLN>`).join('');
 const xml=`<?xml version="1.0" encoding="UTF-8"?><ISO11783_TaskData VersionMajor="4" VersionMinor="3" ManagementSoftwareManufacturer="Parcelles" ManagementSoftwareVersion="10.10" DataTransferOrigin="1"><PFD A="PFD1" C="Parcelle" D="${Math.round(geometryAreaHa(geometry)*10000)}">${boundary}</PFD><VPN A="VPN1" B="0" C="${scale}" D="2" E="${xmlEscape(plan.unit)}"/><TSK A="TSK1" B="${xmlEscape(String(plan.type).slice(0,100))}" E="PFD1" G="1" H="0" I="0" J="0"><TZN A="0" B="Hors prescription - dose nulle"><PDV A="${ddi}" B="0" E="VPN1"/></TZN>${groups.map(g=>`<TZN A="${codes.get(g)}" B="Zone ${xmlEscape(g)}"><PDV A="${ddi}" B="${raw(plan.rates[g])}" E="VPN1"/></TZN>`).join('')}<GRD A="${box[1].toFixed(10)}" B="${box[0].toFixed(10)}" C="${dy}" D="${dx}" E="${columns}" F="${rows}" G="GRD00001" H="${grid.length}" I="1"/></TSK></ISO11783_TaskData>`;return{xml,grid,columns,rows,codes:Object.fromEntries(codes),ddi};
}
export async function isoxmlZip(zones,plan){const {xml,grid}=prescriptionIsoxml(zones,plan);return createZip([{name:'TASKDATA/TASKDATA.XML',data:new Blob([xml])},{name:'TASKDATA/GRD00001.bin',data:new Blob([grid])}]);}

// Mission machine multi-parcelles, dose uniforme : une PFD (contour) et une TSK par parcelle (ISO 11783-10).
// Une TSK par PFD (l'attribut E ne référence qu'un champ) ; produit, dose et VPN sont partagés.
export function missionIsoxml({parcels=[],operation='Travail',product='',dose=null,unit='kg/ha'}={}){
 if(!parcels.length)throw Error('Au moins une parcelle est nécessaire.');
 const spec={'kg/ha':['0006',100,.01],'L/ha':['0001',10000,.0001],'graines/ha':['000B',.1,10]}[unit];if(!spec)throw Error('Unité ISOXML non prise en charge.');
 const [ddi,factor,scale]=spec,xmlEscape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const pfds=parcels.map((parcel,index)=>{const geometry=parcel.geometry,polygons=geometry?.type==='Polygon'?[geometry.coordinates]:geometry?.type==='MultiPolygon'?geometry.coordinates:null;if(!polygons)throw Error(`Contour manquant : ${parcel.nom||parcel.id}`);
  const boundary=polygons.map(poly=>`<PLN A="1">${poly.map((ring,i)=>`<LSG A="${i===0?1:2}">${ring.map(([lon,lat])=>`<PNT A="2" C="${Number(lat).toFixed(10)}" D="${Number(lon).toFixed(10)}"/>`).join('')}</LSG>`).join('')}</PLN>`).join('');
  return `<PFD A="PFD${index+1}" C="${xmlEscape(String(parcel.nom||'Parcelle').slice(0,32))}" D="${Math.round(geometryAreaHa(geometry)*10000)}">${boundary}</PFD>`;}).join('');
 const hasDose=dose!==null&&dose!==''&&Number.isFinite(Number(dose));let rate=null;
 if(hasDose){rate=Math.round(Number(dose)*factor);if(Number(dose)<0||rate>2147483647)throw Error('Dose non représentable dans cette unité ISOXML.');}
 const pdt=product?`<PDT A="PDT1" B="${xmlEscape(String(product).slice(0,32))}"/>`:'';
 const zone=rate!==null?`<TZN A="1" B="Dose uniforme"><PDV A="${ddi}" B="${rate}"${product?' C="PDT1"':''} E="VPN1"/></TZN>`:'';
 const xml=`<?xml version="1.0" encoding="UTF-8"?><ISO11783_TaskData VersionMajor="4" VersionMinor="3" ManagementSoftwareManufacturer="Parcelles" ManagementSoftwareVersion="10.10" DataTransferOrigin="1">${pfds}${pdt}${rate!==null?`<VPN A="VPN1" B="0" C="${scale}" D="2" E="${xmlEscape(unit)}"/>`:''}${parcels.map((_,index)=>`<TSK A="TSK${index+1}" B="${xmlEscape(String(operation).slice(0,32))}" E="PFD${index+1}" G="1"${rate!==null?' H="1"':''}>${zone}</TSK>`).join('')}</ISO11783_TaskData>`;
 return {xml,parcelCount:parcels.length,ddi:rate!==null?ddi:null};
}

