import {geometryBbox,geometryAreaHa,pointInGeometry} from './utils.js';
function intersects(a,b,c,d){const cross=(p,q,r)=>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);const x=cross(a,b,c),y=cross(a,b,d),z=cross(c,d,a),w=cross(c,d,b);return x*y<=0&&z*w<=0&&Math.max(Math.min(a[0],b[0]),Math.min(c[0],d[0]))<=Math.min(Math.max(a[0],b[0]),Math.max(c[0],d[0]))&&Math.max(Math.min(a[1],b[1]),Math.min(c[1],d[1]))<=Math.min(Math.max(a[1],b[1]),Math.max(c[1],d[1]));}
export function containedCell(ring,geometry){if(!ring.slice(0,-1).every(p=>pointInGeometry(p[0],p[1],geometry)))return false;const rings=geometry.type==='Polygon'?geometry.coordinates:geometry.coordinates.flat();for(const boundary of rings){if(boundary.some(p=>p[0]>ring[0][0]&&p[0]<ring[2][0]&&p[1]>ring[0][1]&&p[1]<ring[2][1]))return false;for(let i=1;i<boundary.length;i++)for(let j=1;j<ring.length;j++)if(intersects(boundary[i-1],boundary[i],ring[j-1],ring[j]))return false;}return true;}
export function managementZones(parcel,points,{cellMeters=30,sourceId,sourceType='yield',minSamples=2}={}){
 if(!Number.isInteger(minSamples)||minSamples<1||minSamples>100)throw Error('Nombre d’échantillons invalide.');const bounds=geometryBbox(parcel.geometry);if(!bounds)throw Error('Contour nécessaire.');if(!(cellMeters>=10&&cellMeters<=200))throw Error('Maille autorisée : 10 à 200 m.');const dy=cellMeters/111320,dx=dy/Math.cos((bounds[1]+bounds[3])/2*Math.PI/180),nx=Math.ceil((bounds[2]-bounds[0])/dx),ny=Math.ceil((bounds[3]-bounds[1])/dy);if(nx*ny>2500)throw Error('Augmentez la maille : maximum 2 500 cellules.');
 const buckets=new Map();for(const p of points){const value=p.value??p.yield;if(!Number.isFinite(value)||!pointInGeometry(p.longitude,p.latitude,parcel.geometry))continue;const i=Math.floor((p.longitude-bounds[0])/dx),j=Math.floor((p.latitude-bounds[1])/dy),key=i+':'+j;const b=buckets.get(key)||[];b.push(value);buckets.set(key,b);}
 const cells=[];for(let i=0;i<nx;i++)for(let j=0;j<ny;j++){const values=buckets.get(i+':'+j)||[];if(values.length<minSamples)continue;const x=bounds[0]+i*dx,y=bounds[1]+j*dy,ring=[[x,y],[x+dx,y],[x+dx,y+dy],[x,y+dy],[x,y]];if(!containedCell(ring,parcel.geometry))continue;const geometry={type:'Polygon',coordinates:[ring]};cells.push({id:`${i}:${j}`,geometry,areaHa:geometryAreaHa(geometry),value:values.reduce((s,v)=>s+v,0)/values.length,samples:values.length,enabled:true});}
 if(!cells.length)throw Error('Aucune cellule intérieure suffisamment mesurée. Réduisez la maille ou utilisez un relevé plus dense.');const average=cells.reduce((s,c)=>s+c.value*c.areaHa,0)/cells.reduce((s,c)=>s+c.areaHa,0);for(const c of cells)c.group=c.value<average*.9?'C':c.value>average*1.1?'A':'B';return{version:1,parcelId:parcel.id,geometrySignature:JSON.stringify(parcel.geometry),sourceId,sourceType,cellMeters,minSamples,average,cells,confidence:'Un relevé : potentiel à confirmer sur plusieurs campagnes',method:'Cellules entièrement intérieures, moyenne mesurée ; seuils ±10 % de la moyenne des cellules'};
}
export function zoneSummary(zones){const groups=new Map();for(const c of zones.cells.filter(c=>c.enabled)){const r=groups.get(c.group)||{id:c.group,areaHa:0,total:0,samples:0,cells:0};r.areaHa+=c.areaHa;r.total+=c.value*c.areaHa;r.samples+=c.samples;r.cells++;groups.set(c.group,r);}return [...groups.values()].map(g=>({...g,mean:g.total/g.areaHa,relative:zones.average?100*(g.total/g.areaHa/zones.average-1):null}));}
// Normalize each selected source separately so dense files or different units do not dominate.
export function multiSourceZones(parcel,sources,options={}){if(!sources.length||sources.length>12)throw Error('Choisissez 1 à 12 sources.');if(new Set(sources.map(s=>s.id)).size!==sources.length)throw Error('Source en double.');const cells=new Map(),evidence=[];let template;for(const source of sources){const weight=Number(source.weight??1),direction=Number(source.direction??1);if(!(weight>0&&weight<=100)||![-1,1].includes(direction))throw Error('Poids ou sens invalide.');const zones=managementZones(parcel,source.points,{...options,sourceId:source.id,sourceType:source.type});template=zones;const mean=zones.average,variance=zones.cells.reduce((s,c)=>s+c.areaHa*(c.value-mean)**2,0)/zones.cells.reduce((s,c)=>s+c.areaHa,0),deviation=Math.sqrt(variance);evidence.push({id:source.id,type:source.type,date:source.date||null,weight,direction,mean,deviation,unit:source.unit||'',cells:zones.cells.length});for(const cell of zones.cells){const r=cells.get(cell.id)||{...cell,indicators:[]};r.indicators.push({sourceId:source.id,value:cell.value,samples:cell.samples,z:deviation?Math.max(-2,Math.min(2,(cell.value-mean)/deviation))*direction:0,weight});cells.set(cell.id,r);}}
 const result=[...cells.values()].map(c=>{const weight=c.indicators.reduce((s,x)=>s+x.weight,0),z=c.indicators.reduce((s,x)=>s+x.z*x.weight,0)/weight;return{...c,value:z,samples:c.indicators.reduce((s,x)=>s+x.samples,0),group:z>.5?'A':z<-.5?'C':'B',sourceCount:c.indicators.length,coverage:c.indicators.length/sources.length};});const years=new Set(evidence.filter(e=>e.type==='yield'&&/^\d{4}-\d{2}-\d{2}$/.test(e.date||'')).map(e=>e.date.slice(0,4)));return{...template,sourceType:'multi',sourceId:null,sources:evidence,average:0,cells:result,confidence:years.size>=3?'Historique sur 3 années ou plus ; classement relatif, pas une causalité':'Confiance limitée : historique ou sources incomplets',method:'Moyenne pondérée des écarts standardisés par source (bornés à ±2) ; A > +0,5 ; C < −0,5 ; B sinon. Sens et poids validés par l’utilisateur. Sources manquantes non imputées.'};}
