import {loadSpatialSource} from './spatial-analysis.js';
import {shapefileZip,isoxmlZip} from './machine-export.js';
import {actualWorkPatch} from './prescriptions.js';
import {escapeHtml as e,uid,downloadBlob,pointInGeometry} from './utils.js';
import {YieldRepository,analyzeYield,readYieldFiles,numeric,YIELD_FIELDS} from './yield.js';
import {managementZones,multiSourceZones,zoneSummary} from './management-zones.js';
import {prescription,prescriptionGeoJson,exportPrescription,compareActual,resultCorrelation} from './prescriptions.js';
import {farmRecords,saveFarmRecord,decide} from './farm-records.js';
import {createZip} from './zip-lite.js';
import {active} from './farm-memory.js';
let scope='',draft=null,zoneRecord=null,plan=null,undo=[],redo=[],applied=null,outcome=null;
const colors={A:'#287b49',B:'#d5aa38',C:'#bc6440'};
export async function precisionAction(action,control,c){const{host,show,button,fmt,data,parcel,featuresOnMap}=c,{store}=host,p=parcel();const nextScope=store.workspaceContext().key;if(scope!==nextScope){scope=nextScope;draft=zoneRecord=plan=applied=outcome=null;undo=[];redo=[];}
 const records=kind=>farmRecords(data(),kind).filter(r=>r.parcelId===p?.id),choose=(id,kind)=>records(kind).find(r=>r.id===id),option=(rows,selected='')=>rows.map(r=>`<option value="${e(r.id)}" ${r.id===selected?'selected':''}>${e(r.name||r.id)} · ${new Date(r.updatedAt||r.createdAt).toLocaleDateString('fr-FR')}</option>`).join('');
 const requireParcel=()=>{if(!p)throw Error('Sélectionnez une parcelle.');};
 const zoneEvidence=group=>!draft.sources?'':draft.sources.map(source=>{const values=draft.cells.filter(cell=>cell.enabled&&cell.group===group).map(cell=>({cell,indicator:cell.indicators?.find(i=>i.sourceId===source.id)})).filter(r=>r.indicator);const area=values.reduce((sum,r)=>sum+r.cell.areaHa,0),mean=area?values.reduce((sum,r)=>sum+r.cell.areaHa*r.indicator.value,0)/area:null;return `<p>${e(store.get('documents',source.id)?.name||source.type)} : ${mean===null?'non mesuré':fmt(mean)+' '+e(source.unit)} · ${fmt(area)} ha documentés.</p>`;}).join('');
 const editZones=()=>{show('Zones · '+p.nom,`<p>${e(draft.method)}. ${e(draft.confidence)}</p>${draft.sources?`<details><summary>Sources et hypothèses</summary>${draft.sources.map(s=>`<p>${e(s.id)} · ${e(s.type)} · ${e(s.date||'non daté')} · poids ${s.weight}, sens ${s.direction}, moyenne ${fmt(s.mean)} ${e(s.unit)}</p>`).join('')}</details>`:''}<p>Surface représentée : ${fmt(zoneSummary(draft).reduce((s,g)=>s+g.areaHa,0))} ha / ${fmt(p.surfaceHa)} ha déclarés. Les bords et cellules sans mesures restent hors préconisation.</p>${zoneSummary(draft).map(g=>`<article class="yield-import"><strong>Zone ${e(g.id)} · ${fmt(g.areaHa)} ha</strong><details><summary>Pourquoi cette zone ?</summary><p>${draft.sources?`Score standardisé moyen ${fmt(g.mean)} ; A au-dessus de +0,5, C sous −0,5, B entre les deux. Poids et sens choisis par l’utilisateur, sans substitution des mesures absentes.`:`Rendement moyen ${fmt(g.mean)} t/ha ; ${fmt(g.relative)} % par rapport aux cellules mesurées.`} ${g.samples} échantillons. Les affectations manuelles peuvent modifier le classement initial.</p>${zoneEvidence(g.id)}</details></article>`).join('')}<details><summary>Ajuster les limites / regrouper les cellules</summary><p>Limites ajustables à la maille choisie. Désactivez une cellule ou affectez-la à un autre groupe. Aucun contour n’est déplacé arbitrairement.</p><label>Page<input id="zone-page" type="number" min="1" max="${Math.ceil(draft.cells.length/50)}" value="1"></label><div id="zone-cells"></div></details><div class="satellite-actions">${button('zone-undo','Annuler',undo.length?'':'disabled')}${button('zone-redo','Rétablir',redo.length?'':'disabled')}${button('zones-map','Voir les zones')}</div>`,button('zones-save','Valider les zones'));const renderCells=()=>{const page=Math.max(1,Number(document.querySelector('#zone-page').value)||1),cells=draft.cells.slice((page-1)*50,page*50);document.querySelector('#zone-cells').innerHTML=cells.map(cell=>`<label>${e(cell.id)} · ${fmt(cell.value)}<select data-cell="${e(cell.id)}"><option value="off" ${!cell.enabled?'selected':''}>Hors préconisation</option>${['A','B','C'].map(g=>`<option ${cell.enabled&&cell.group===g?'selected':''}>${g}</option>`).join('')}</select></label>`).join('');document.querySelectorAll('[data-cell]').forEach(select=>select.onchange=()=>{undo.push(structuredClone(draft));undo=undo.slice(-15);redo=[];const cell=draft.cells.find(x=>x.id===select.dataset.cell);cell.enabled=select.value!=='off';if(cell.enabled)cell.group=select.value;editZones();});};document.querySelector('#zone-page').onchange=renderCells;renderCells();};
 if(action==='zones'){requireParcel();const docs=data().documents.filter(d=>!d.deletedAt&&d.parcelId===p.id&&(d.yieldMap||d.spatialSource));show('Zones de gestion',`<p>${e(p.nom)} · classement explicable à partir des relevés spatiaux sélectionnés. Aucun potentiel agronomique certain n’est déduit d’une seule campagne.</p><label>Source principale<select id="zone-source">${option(docs)}</select></label><details><summary>Ajouter des sources / campagnes</summary>${docs.map(d=>`<label><input type="checkbox" name="extra-zone-source" value="${e(d.id)}"> ${e(d.name)}</label><label>Poids <input type="number" min="0.1" max="100" step="any" data-source-weight="${e(d.id)}" value="1"></label>`).join('')}</details>${button('spatial-import','Importer NDVI / NDMI / sol / topographie')}<label>Maille (m)<input id="zone-size" type="number" min="10" max="200" value="30"></label><label>Échantillons minimum par cellule<input id="zone-samples" type="number" min="1" max="100" value="2"></label>${button('zones-build','Proposer des zones',docs.length?'':'disabled')}<h3>Zones enregistrées</h3>${records('zones').map(r=>`<p>${e(r.name)} ${button('zones-edit','Ouvrir',`data-id="${e(r.id)}"`)}</p>`).join('')}`);}
 else if(action==='zones-build'){const doc=store.get('documents',document.querySelector('#zone-source').value),cellMeters=Number(document.querySelector('#zone-size').value),minSamples=Number(document.querySelector('#zone-samples').value);if(!doc)throw Error('Relevé spatial nécessaire.');const ids=[...new Set([doc.id,...[...document.querySelectorAll('[name=extra-zone-source]:checked')].map(x=>x.value)])],weights=new Map([...document.querySelectorAll('[data-source-weight]')].map(x=>[x.dataset.sourceWeight,Number(x.value)])),sources=[];for(const id of ids){const source=await loadSpatialSource(store,store.get('documents',id),p);sources.push({...source,weight:weights.get(id)??1});}if(scope!==store.workspaceContext().key)throw Error('Exploitation changée.');draft=sources.length===1&&sources[0].type==='yield'?managementZones(p,sources[0].points,{cellMeters,minSamples,sourceId:doc.id}):multiSourceZones(p,sources,{cellMeters,minSamples});zoneRecord=null;undo=[];redo=[];editZones();}
 else if(action==='zones-edit'){zoneRecord=choose(control.dataset.id,'zones');if(!zoneRecord)throw Error('Zones introuvables.');draft=structuredClone(zoneRecord.zones);undo=[];redo=[];editZones();}
 else if(action==='zone-undo'||action==='zone-redo'){const from=action==='zone-undo'?undo:redo,to=action==='zone-undo'?redo:undo;if(from.length){to.push(structuredClone(draft));draft=from.pop();}editZones();}
 else if(action==='zones-map'){if(!draft)throw Error('Préparez les zones.');featuresOnMap(draft.cells.filter(x=>x.enabled).map(cell=>({type:'Feature',geometry:cell.geometry,properties:{zone:cell.group,valeur:cell.value,color:colors[cell.group]}})),'Zones · '+p.nom);}
 else if(action==='zones-save'){if(!draft||draft.parcelId!==p.id||draft.geometrySignature!==JSON.stringify(p.geometry))throw Error('Contour changé : recalculez les zones.');if(!zoneSummary(draft).length)throw Error('Aucune cellule active.');zoneRecord=await saveFarmRecord(store,'zones',{name:'Zones '+p.nom,parcelId:p.id,zones:draft},zoneRecord);show('Zones enregistrées',`<p>${e(zoneRecord.name)} · version ${zoneRecord.version}</p>`,button('prescriptions','Préparer une préconisation'));}
 else if(action==='prescriptions'){requireParcel();const rows=records('zones');show('Préconisations modulées',`<label>Zones validées<select id="prescription-zones">${option(rows)}</select></label>${button('prescription-new','Préparer les doses',rows.length?'':'disabled')}<h3>Préconisations enregistrées</h3>${records('prescription').map(r=>`<p>${e(r.name)} · ${fmt(r.plan.quantity)} ${e(r.plan.unit.replace('/ha',''))} ${button('prescription-open','Ouvrir',`data-id="${e(r.id)}"`)}</p>`).join('')}`);}
 else if(action==='prescription-new'||action==='prescription-open'){const saved=action==='prescription-open'?choose(control.dataset.id,'prescription'):null;zoneRecord=saved?choose(saved.zoneId,'zones'):choose(document.querySelector('#prescription-zones').value,'zones');if(!zoneRecord)throw Error('Zones nécessaires.');draft=saved?.zoneSnapshot||structuredClone(zoneRecord.zones);plan=saved||null;const groups=zoneSummary(draft),value=saved?.plan;show('Éditeur de préconisation',`<form id="prescription-form" class="form-grid"><label>Travail<input name="type" required value="${e(value?.type||'Semis')}"></label><label>Unité<select name="unit">${['kg/ha','L/ha','graines/ha'].map(u=>`<option ${value?.unit===u?'selected':''}>${u}</option>`).join('')}</select></label><label>Dose uniforme de référence<input name="reference" type="number" min="0" step="any" required value="${value?.reference??''}"></label>${groups.map(g=>`<label>Zone ${e(g.id)} · ${fmt(g.areaHa)} ha<input name="rate-${e(g.id)}" type="number" min="0" step="any" required value="${value?.rates[g.id]??''}"></label>`).join('')}</form><p>Définissez chaque dose. Aucune dose agronomique automatique n’est imposée. Pour fusionner des groupes ou ajuster leurs limites, revenez aux zones.</p><div id="prescription-totals"></div>`,button('prescription-calculate','Calculer les quantités'));}
 else if(action==='prescription-calculate'){const form=document.querySelector('#prescription-form');if(!form.reportValidity())return;const v=new FormData(form),rates=Object.fromEntries(zoneSummary(draft).map(g=>[g.id,Number(v.get('rate-'+g.id))])),calculated=prescription(draft,{type:v.get('type'),reference:Number(v.get('reference')),unit:v.get('unit'),rates});plan={...plan,plan:calculated,zoneId:zoneRecord.id,zoneVersion:zoneRecord.version,zoneSnapshot:structuredClone(draft),parcelId:p.id,name:calculated.type+' · '+p.nom};document.querySelector('#prescription-totals').innerHTML=`<p>Moyenne : ${fmt(calculated.mean)} ${e(calculated.unit)} · total : ${fmt(calculated.quantity)} ${e(calculated.unit.replace('/ha',''))}</p><p>Uniforme : ${fmt(calculated.uniformQuantity)} · écart : ${fmt(calculated.difference)}</p>${calculated.groups.map(g=>`<p>Zone ${e(g.id)} : ${fmt(g.quantity)}</p>`).join('')}${button('prescription-save','Valider et enregistrer')}`;form.oninput=()=>{document.querySelector('#prescription-totals').innerHTML='<p>Recalculez après modification.</p>';plan=null;};}
 else if(action==='prescription-save'){if(!plan?.plan)throw Error('Recalculez la préconisation.');const current=store.get('integrationImports',plan.zoneId);if(!current||current.version!==plan.zoneVersion)throw Error('Les zones ont changé : rouvrez la préconisation.');plan=await saveFarmRecord(store,'prescription',plan,plan.id?plan:null);await decide(store,{parcelId:p.id,problem:'Modulation par zones',evidence:{zoneId:plan.zoneId,zoneVersion:plan.zoneVersion},proposal:plan.plan,decision:'Préconisation validée',workId:null});show('Préconisation validée',`<p>${e(plan.name)} · ${fmt(plan.plan.quantity)} ${e(plan.plan.unit.replace('/ha',''))}</p><p>GeoJSON est un format géographique standard. Vérifiez son acceptation par votre terminal avant transfert. SHP WGS84 et ISOXML v4.3 grille type 1 disponibles. ISOXML : dose nulle hors cellules actives ou en perte de position ; vérifier les réglages et compatibilités du terminal avant application. Aucun essai matériel réel effectué.</p>`,button('prescription-export','Exporter GeoJSON')+button('prescription-shp','Exporter SHP')+button('prescription-isoxml','Exporter ISOXML')+button('prescription-work','Préparer le travail')+button('prescription-map','Voir sur carte'));}
 else if(action==='prescription-shp'||action==='prescription-isoxml'){if(!plan?.plan)throw Error('Préconisation nécessaire.');downloadBlob(action==='prescription-shp'?'prescription-shp.zip':'prescription-isoxml.zip',await(action==='prescription-shp'?shapefileZip:isoxmlZip)(plan.zoneSnapshot||draft,plan.plan));}
 else if(action==='prescription-export'){if(!plan?.plan)throw Error('Préconisation nécessaire.');downloadBlob('preconisation.geojson',new Blob([exportPrescription('geojson',plan.zoneSnapshot||draft,plan.plan)],{type:'application/geo+json'}));}
 else if(action==='prescription-map'){featuresOnMap(prescriptionGeoJson(plan.zoneSnapshot||draft,plan.plan).features.map(f=>({...f,properties:{...f.properties,color:colors[f.properties.zone]}})),'Préconisation · '+p.nom);}
 else if(action==='prescription-work'){host.closeModal();host.openWork({parcelId:p.id,type:plan.plan.type,dose:plan.plan.mean,doseUnit:plan.plan.unit,surfaceWorked:plan.plan.areaHa,status:'À préparer',prescriptionId:plan.id,plannedMetrics:{areaHa:plan.plan.areaHa,dose:plan.plan.mean,duration:null},note:'Préconisation '+plan.id+' · uniquement sur les cellules validées.'});}
 else if(action==='actual'){requireParcel();show('Travail prévu / réalisé',`<label>Intervention<select id="actual-work">${option(active(data(),'interventions').filter(w=>w.parcelId===p.id).map(w=>({...w,name:w.type+' · '+w.date})))}</select></label>${button('actual-open','Saisir / comparer')}`);}
 else if(action==='actual-open'){const w=store.get('interventions',document.querySelector('#actual-work').value);if(!w)throw Error('Travail nécessaire.');show('Prévu / réalisé · '+w.type,`<form id="actual-form" data-id="${e(w.id)}" class="form-grid">${[['areaHa','Surface (ha)'],['dose','Dose (unité du travail)'],['duration','Durée (h)']].flatMap(([key,label])=>['planned','actual'].map(side=>`<label>${side==='planned'?'Prévu':'Réalisé'} · ${label}<input name="${side}-${key}" type="number" min="0" step="any" value="${w[side+'Metrics']?.[key]??''}"></label>`)).join('')}</form><p>Après validation, les mesures réelles renseigneront la surface, la dose et la durée du travail. Les coûts saisis, stocks et compteurs matériel restent à vérifier dans leurs formulaires.</p>`,button('actual-save','Valider ces mesures'));}
 else if(action==='actual-save'){const form=document.querySelector('#actual-form');if(!form.reportValidity())return;const w=store.get('interventions',form.dataset.id),values=new FormData(form),metrics=side=>Object.fromEntries(['areaHa','dose','duration'].map(k=>[k,numeric(values.get(side+'-'+k))]));const plannedMetrics=metrics('planned'),actualMetrics=metrics('actual');if([...Object.values(plannedMetrics),...Object.values(actualMetrics)].some(v=>v!==null&&v<0))throw Error('Valeur négative interdite.');const saved=await store.upsert('interventions',actualWorkPatch(w,plannedMetrics,actualMetrics),{label:'Mesures prévues / réelles validées.'}),comparison=compareActual(saved);show('Écarts mesurés',Object.entries(comparison).map(([k,r])=>`<p>${e(k)} : prévu ${fmt(r.planned)}, réel ${fmt(r.actual)}, écart ${fmt(r.percent)} %</p>`).join(''),button('edit-work','Ouvrir le travail',`data-id="${e(saved.id)}"`)+(saved.status==='Terminé'?button('effects','Répercuter sur stocks / heures',`data-id="${e(saved.id)}"`):''));}
 else if(action==='results'){requireParcel();const cache=await store.storage.get('satellite-cache-v1')||[],key=store.workspaceContext().key;const entries=cache.filter(x=>x.parcelId===p.id&&(()=>{try{const ident=JSON.parse(x.key);return ident[0][0]===key&&ident[0][1]===(host.sync.user?.uid||'local')&&JSON.stringify(ident[3])===JSON.stringify(p.geometry);}catch{return false;}})());const series=[...new Map(entries.flatMap(x=>x.series||[]).map(r=>[r.date,r])).values()];outcome={parcelId:p.id,series};show('Résultats observés',`<label>Intervention<select id="result-work">${option(active(data(),'interventions').filter(w=>w.parcelId===p.id&&w.status==='Terminé').map(w=>({...w,name:w.type+' · '+w.date})))}</select></label>${button('zone-results','Comparer deux groupes de zones')}<p>${series.length} observations satellite mises en cache. Comparaison à l’échelle de la parcelle, pas d’une zone non mesurée.</p>${button('result-calculate','Comparer avant / après')}<div id="result-values"></div>`);}
 else if(action==='result-calculate'){const w=store.get('interventions',document.querySelector('#result-work').value);if(!w)throw Error('Intervention terminée nécessaire.');const r=resultCorrelation(outcome.series,w.date);r.harvests=farmRecords(data(),'harvest').filter(l=>l.parcelId===p.id&&l.date>=w.date&&l.date.slice(0,4)===w.date.slice(0,4)).map(l=>({id:l.id,date:l.date,quantity:l.quantity,unit:l.unit,code:l.code}));outcome={...outcome,workId:w.id,result:r};document.querySelector('#result-values').innerHTML=`<p>Avant : ${r.before?e(r.before.date)+' · '+fmt(r.before.ndvi):'Pas de mesure dans les 21 jours précédents'}</p><p>Après : ${r.after?e(r.after.date)+' · '+fmt(r.after.ndvi):'Pas de mesure dans les 35 jours suivants'}</p><p>Évolution : ${fmt(r.percent)} %</p><p>${e(r.conclusion)}</p>${r.harvests.map(l=>`<p>Lot récolté ensuite : ${e(l.code)} · ${e(l.date)} · ${fmt(l.quantity)} ${e(l.unit)}. Pas d’attribution causale à ce travail.</p>`).join('')}${button('result-save','Conserver cette analyse')}`;}
 else if(action==='result-save'){if(!outcome?.result)throw Error('Comparez d’abord les mesures.');await decide(store,{parcelId:p.id,problem:'Évolution après intervention',evidence:{before:outcome.result.before||null,after:outcome.result.after||null},proposal:null,decision:'Analyse consultée et conservée',workId:outcome.workId,result:outcome.result});show('Analyse conservée','<p>Accessible dans la mémoire des décisions.</p>');}
 else if(action==='decisions'){show('Mémoire des décisions',records('decision').sort((a,b)=>b.at-a.at).map(r=>`<article class="yield-import"><small>${new Date(r.at).toLocaleString('fr-FR')}</small><strong>${e(r.problem)}</strong><p>${e(r.decision)}</p><details><summary>Données et résultat</summary><pre class="farm-json">${e(JSON.stringify({evidence:r.evidence,proposal:r.proposal,workId:r.workId,result:r.result},null,2))}</pre></details></article>`).join('')||'<p>Aucune décision enregistrée pour cette parcelle.</p>');}
 else return false;
 return true;
}
