import {zoneSummary} from './management-zones.js';
export function prescription(zones,{reference,unit,type,rates}){if(!Number.isFinite(reference)||reference<0||!['kg/ha','L/ha','graines/ha'].includes(unit)||!type)throw Error('Dose, unité et type obligatoires.');const groups=zoneSummary(zones).map(g=>{const rate=rates[g.id];if(!Number.isFinite(rate)||rate<0)throw Error('Chaque zone doit recevoir une dose positive ou nulle.');return{...g,rate,quantity:g.areaHa*rate};});const areaHa=groups.reduce((s,g)=>s+g.areaHa,0),quantity=groups.reduce((s,g)=>s+g.quantity,0);if(!areaHa)throw Error('Aucune zone active.');return{version:1,parcelId:zones.parcelId,type,reference,unit,rates,groups,areaHa,quantity,mean:quantity/areaHa,uniformQuantity:reference*areaHa,difference:quantity-reference*areaHa};}
export function prescriptionGeoJson(zones,plan){return{type:'FeatureCollection',features:zones.cells.filter(c=>c.enabled).map(c=>({type:'Feature',geometry:c.geometry,properties:{zone:c.group,cell:c.id,rate:plan.rates[c.group],unit:plan.unit,type:plan.type,area_ha:c.areaHa}}))};}
export const MACHINE_EXPORTS={geojson:{label:'GeoJSON WGS84',extension:'geojson',mime:'application/geo+json'},shp:{label:'SHP WGS84',extension:'zip',mime:'application/zip',export:async(z,p)=>(await import('./machine-export.js')).shapefileZip(z,p)},isoxml:{label:'ISOXML 4.3 · grille type 1',extension:'zip',mime:'application/zip',export:async(z,p)=>(await import('./machine-export.js')).isoxmlZip(z,p)}};
export function exportPrescription(format,zones,plan){if(format!=='geojson')throw Error('Utilisez le convertisseur ZIP dédié pour SHP ou ISOXML.');return JSON.stringify(prescriptionGeoJson(zones,plan),null,2);}
export function compareActual(work){const planned=work.plannedMetrics||{},actual=work.actualMetrics||{},row=(key)=>{const p=planned[key],a=actual[key];return{planned:Number.isFinite(p)?p:null,actual:Number.isFinite(a)?a:null,difference:Number.isFinite(p)&&Number.isFinite(a)?a-p:null,percent:Number.isFinite(p)&&p!==0&&Number.isFinite(a)?100*(a-p)/p:null};};return{area:row('areaHa'),dose:row('dose'),duration:row('duration')};}
export function resultCorrelation(series,date,{beforeDays=21,afterDays=35}={}){const t=Date.parse(date);if(!Number.isFinite(t))throw Error('Date d’intervention nécessaire.');const good=series.filter(r=>r.usable&&Number.isFinite(r.ndvi)),before=good.filter(r=>Date.parse(r.date)<t&&Date.parse(r.date)>=t-beforeDays*86400000).sort((a,b)=>b.date.localeCompare(a.date))[0],after=good.filter(r=>Date.parse(r.date)>t&&Date.parse(r.date)<=t+afterDays*86400000).sort((a,b)=>a.date.localeCompare(b.date))[0];return{before,after,change:before&&after?after.ndvi-before.ndvi:null,percent:before&&after&&before.ndvi!==0?100*(after.ndvi-before.ndvi)/Math.abs(before.ndvi):null,conclusion:'Association temporelle seulement : météo, culture et autres interventions peuvent expliquer l’évolution.'};}
// Actual measurements feed the existing work fields; manually entered costs stay intact.
export function actualWorkPatch(work,plannedMetrics,actualMetrics){const patch={...work,plannedMetrics,actualMetrics};for(const [key,field]of [['areaHa','surfaceWorked'],['dose','dose'],['duration','duration']])if(actualMetrics[key]!==null)patch[field]=actualMetrics[key];patch.actualMeasuredAt=Date.now();patch.costReviewRequired=['areaHa','dose','duration'].some(k=>actualMetrics[k]!==null&&actualMetrics[k]!==work.actualMetrics?.[k]);return patch;}
