import {escapeHtml, formatEuro, formatNumber, localDate, toNumber, campaignFor} from './utils.js';
import {documentContextText, documentSummary, filterDocuments, traceabilityRows, traceabilitySummary} from './traceability.js';
function shell(title,body){return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(title)}</title><style>body{font-family:system-ui,-apple-system,sans-serif;margin:32px;color:#13251c}h1,h2{color:#155c3a}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.kpis{display:flex;gap:20px;flex-wrap:wrap}.kpi{padding:14px 18px;border:1px solid #ddd;border-radius:12px}.muted{color:#667}@media print{button{display:none}body{margin:12mm}}</style></head><body>${body}<script>window.addEventListener('load',()=>document.getElementById('print')?.addEventListener('click',()=>print()))<\/script></body></html>`}
export function farmReportHtml(state){
 const active=t=>(state[t]||[]).filter(x=>!x.deletedAt);const parcels=active('parcelles').filter(p=>(p.ownershipType||'own')==='own'),works=active('interventions');const area=parcels.reduce((s,p)=>s+toNumber(p.surfaceHa),0),campaign=campaignFor();const cw=works.filter(w=>(w.campaignId||campaignFor(w.date))===campaign),cost=cw.reduce((s,w)=>s+toNumber(w.cost),0);const cultures={};parcels.forEach(p=>cultures[p.culture||'Sans culture']=(cultures[p.culture||'Sans culture']||0)+toNumber(p.surfaceHa));
 return shell(`Rapport ${state.exploitation?.nom||'Parcelles'}`,`<h1>${escapeHtml(state.exploitation?.nom||'Parcelles')}</h1><p class="muted">Campagne ${escapeHtml(campaign)} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${parcels.length}</strong><br>parcelles</div><div class="kpi"><strong>${formatNumber(area)} ha</strong><br>surface</div><div class="kpi"><strong>${cw.length}</strong><br>travaux</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coûts saisis</div></div><h2>Assolement</h2><table><thead><tr><th>Culture</th><th>Surface</th><th>%</th></tr></thead><tbody>${Object.entries(cultures).sort((a,b)=>b[1]-a[1]).map(([c,a])=>`<tr><td>${escapeHtml(c)}</td><td>${formatNumber(a)} ha</td><td>${area?formatNumber(a/area*100):0} %</td></tr>`).join('')}</tbody></table><h2>Travaux de campagne</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Parcelle</th><th>Coût</th></tr></thead><tbody>${cw.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(w=>{const p=parcels.find(p=>p.id===w.parcelId)||(state.parcelles||[]).find(p=>p.id===w.parcelId);return`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(p?.nom||'—')}</td><td>${formatEuro(w.cost)}</td></tr>`}).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}
export function parcelReportHtml(state,parcelId){const p=(state.parcelles||[]).find(x=>x.id===parcelId);if(!p)return'';const works=(state.interventions||[]).filter(w=>!w.deletedAt&&w.parcelId===parcelId).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return shell(`Parcelle ${p.nom}`,`<h1>${escapeHtml(p.nom)}</h1><p>${escapeHtml(p.culture||'Culture non renseignée')} · ${formatNumber(p.surfaceHa)} ha · ${escapeHtml(p.commune||'')}</p>${p.notes?`<p><strong>Note :</strong> ${escapeHtml(p.notes)}</p>`:''}<h2>Historique</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Produit</th><th>Coût</th><th>Note</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(w.product||'')}</td><td>${formatEuro(w.cost)}</td><td>${escapeHtml(w.note||'')}</td></tr>`).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`)}
export function openPrintableReport(html){const blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),win=window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return Boolean(win);}

export function clientReportHtml(state,clientId){
 const client=(state.clients||[]).find(x=>x.id===clientId&&!x.deletedAt);if(!client)return'';
 const parcels=(state.parcelles||[]).filter(p=>!p.deletedAt&&p.clientId===clientId),ids=new Set(parcels.map(p=>p.id));
 const works=(state.interventions||[]).filter(w=>!w.deletedAt&&ids.has(w.parcelId)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const area=parcels.reduce((s,p)=>s+toNumber(p.surfaceHa),0),cost=works.reduce((s,w)=>s+toNumber(w.cost),0);
 return shell(`Client ${client.name}`,`<h1>${escapeHtml(client.name||'Client')}</h1><p class="muted">${escapeHtml(client.contact||client.phone||client.email||'')}</p><div class="kpis"><div class="kpi"><strong>${parcels.length}</strong><br>parcelles</div><div class="kpi"><strong>${formatNumber(area)} ha</strong><br>surface</div><div class="kpi"><strong>${works.length}</strong><br>travaux</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coûts saisis</div></div><h2>Parcelles</h2><table><thead><tr><th>Parcelle</th><th>Culture</th><th>Surface</th><th>Commune</th></tr></thead><tbody>${parcels.map(p=>`<tr><td>${escapeHtml(p.nom)}</td><td>${escapeHtml(p.culture||'')}</td><td>${formatNumber(p.surfaceHa)} ha</td><td>${escapeHtml(p.commune||'')}</td></tr>`).join('')}</tbody></table><h2>Travaux</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Parcelle</th><th>Coût</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date||w.plannedDate)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(parcels.find(p=>p.id===w.parcelId)?.nom||'')}</td><td>${formatEuro(w.cost)}</td></tr>`).join('')}</tbody></table>${client.note?`<h2>Note</h2><p>${escapeHtml(client.note)}</p>`:''}<button id="print">Imprimer / PDF</button>`);
}

export function equipmentReportHtml(state,equipmentId){
 const m=(state.materiels||[]).find(x=>x.id===equipmentId&&!x.deletedAt);if(!m)return'';
 const works=(state.interventions||[]).filter(w=>!w.deletedAt&&(w.equipmentId===equipmentId||w.machineId===equipmentId)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const records=(state.maintenanceRecords||[]).filter(r=>!r.deletedAt&&r.equipmentId===equipmentId).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const hours=works.reduce((s,w)=>s+toNumber(w.duration??w.durationHours),0),cost=works.reduce((s,w)=>s+toNumber(w.machineCost),0),maint=records.reduce((s,r)=>s+toNumber(r.cost),0),fixed=toNumber(m.insurance)+toNumber(m.amortization),known=cost+maint+fixed;
 return shell(`Matériel ${m.nom}`,`<h1>${escapeHtml(m.nom||'Matériel')}</h1><p class="muted">Compteur ${formatNumber(m.currentMeter)} h · prochain entretien ${formatNumber(m.maintenanceDue)} h</p><div class="kpis"><div class="kpi"><strong>${works.length}</strong><br>travaux</div><div class="kpi"><strong>${formatNumber(hours)} h</strong><br>durée saisie</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coût machine travaux</div><div class="kpi"><strong>${formatEuro(maint)}</strong><br>entretiens</div><div class="kpi"><strong>${formatEuro(fixed)}</strong><br>fixes annuels</div><div class="kpi"><strong>${formatEuro(known)}</strong><br>coût connu</div></div><h2>Entretiens</h2><table><thead><tr><th>Date</th><th>Compteur</th><th>Opération</th><th>Coût</th></tr></thead><tbody>${records.map(r=>`<tr><td>${localDate(r.date)}</td><td>${formatNumber(r.meter)} h</td><td>${escapeHtml(r.type||r.note||'')}</td><td>${formatEuro(r.cost)}</td></tr>`).join('')}</tbody></table><h2>Utilisation</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Durée</th><th>Coût machine</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${formatNumber(w.duration??w.durationHours)} h</td><td>${formatEuro(w.machineCost)}</td></tr>`).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}

export function pilotageReportHtml(state,campaign=campaignFor()){
 const own=(state.parcelles||[]).filter(p=>!p.deletedAt&&(p.ownershipType||'own')==='own'&&!p.archived);
 const works=(state.interventions||[]).filter(w=>!w.deletedAt&&(w.campaignId||campaignFor(w.date||w.plannedDate))===campaign&&w.status!=='Annulé');
 const rows=own.map(p=>{
   const area=toNumber(p.surfaceHa),e=p.economicsByCampaign?.[campaign]||(campaign===campaignFor()?p.economics:null)||{},pw=works.filter(w=>w.parcelId===p.id),workCost=pw.reduce((s,w)=>s+toNumber(w.cost),0),manualHa=toNumber(e.inputCostHa)+toNumber(e.operatorCostHa)+toNumber(e.otherCostHa),charges=workCost+manualHa*area,productHa=toNumber(e.productHa)||(toNumber(e.yield)&&toNumber(e.salePrice)?toNumber(e.yield)*toNumber(e.salePrice):0),gross=productHa*area,margin=gross-charges;
   return{p,area,workCost,charges,productHa,gross,margin,marginHa:area?margin/area:0};
 });
 const area=rows.reduce((s,r)=>s+r.area,0),gross=rows.reduce((s,r)=>s+r.gross,0),charges=rows.reduce((s,r)=>s+r.charges,0),margin=gross-charges;
 const cultureMap={};for(const r of rows){const c=r.p.culture||'Non renseignée';const x=cultureMap[c]||(cultureMap[c]={area:0,gross:0,charges:0,margin:0});x.area+=r.area;x.gross+=r.gross;x.charges+=r.charges;x.margin+=r.margin;}
 return shell(`Pilotage ${campaign}`,`<h1>Pilotage de campagne</h1><p class="muted">${escapeHtml(state.exploitation?.nom||'Parcelles')} · campagne ${escapeHtml(campaign)} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${formatNumber(area)} ha</strong><br>surface</div><div class="kpi"><strong>${formatEuro(gross)}</strong><br>produit brut estimé</div><div class="kpi"><strong>${formatEuro(charges)}</strong><br>charges saisies</div><div class="kpi"><strong>${formatEuro(margin)}</strong><br>marge brute estimée</div><div class="kpi"><strong>${formatEuro(area?margin/area:0)}/ha</strong><br>marge moyenne</div></div><h2>Par culture</h2><table><thead><tr><th>Culture</th><th>Surface</th><th>Produit</th><th>Charges</th><th>Marge</th><th>Marge/ha</th></tr></thead><tbody>${Object.entries(cultureMap).sort((a,b)=>b[1].area-a[1].area).map(([c,x])=>`<tr><td>${escapeHtml(c)}</td><td>${formatNumber(x.area)} ha</td><td>${formatEuro(x.gross)}</td><td>${formatEuro(x.charges)}</td><td>${formatEuro(x.margin)}</td><td>${formatEuro(x.area?x.margin/x.area:0)}</td></tr>`).join('')}</tbody></table><h2>Par parcelle</h2><table><thead><tr><th>Parcelle</th><th>Culture</th><th>Surface</th><th>Produit/ha</th><th>Charges</th><th>Marge</th><th>Marge/ha</th></tr></thead><tbody>${rows.sort((a,b)=>b.margin-a.margin).map(r=>`<tr><td>${escapeHtml(r.p.nom)}</td><td>${escapeHtml(r.p.culture||'')}</td><td>${formatNumber(r.area)} ha</td><td>${formatEuro(r.productHa)}</td><td>${formatEuro(r.charges)}</td><td>${formatEuro(r.margin)}</td><td>${formatEuro(r.marginHa)}</td></tr>`).join('')}</tbody></table><p class="muted">Estimations de pilotage basées uniquement sur les données saisies dans Parcelles. Elles ne remplacent pas la comptabilité.</p><button id="print">Imprimer / PDF</button>`);
}

export function stockReportHtml(state){
 const items=(state.stockItems||[]).filter(x=>!x.deletedAt),movements=(state.stockMovements||[]).filter(x=>!x.deletedAt).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
 const value=items.reduce((s,x)=>s+toNumber(x.quantity)*toNumber(x.unitPrice),0);
 return shell('État des stocks',`<h1>État des stocks</h1><p class="muted">${escapeHtml(state.exploitation?.nom||'Parcelles')} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${items.length}</strong><br>articles</div><div class="kpi"><strong>${formatEuro(value)}</strong><br>valeur estimée</div></div><h2>Stocks</h2><table><thead><tr><th>Produit</th><th>Catégorie</th><th>Quantité</th><th>Prix unitaire</th><th>Valeur</th><th>Seuil</th></tr></thead><tbody>${items.map(x=>`<tr><td>${escapeHtml(x.name||'')}</td><td>${escapeHtml(x.category||'')}</td><td>${formatNumber(x.quantity)} ${escapeHtml(x.unit||'')}</td><td>${formatEuro(x.unitPrice)}</td><td>${formatEuro(toNumber(x.quantity)*toNumber(x.unitPrice))}</td><td>${x.alertBelow===null||x.alertBelow===undefined?'—':`${formatNumber(x.alertBelow)} ${escapeHtml(x.unit||'')}`}</td></tr>`).join('')}</tbody></table><h2>Derniers mouvements</h2><table><thead><tr><th>Date</th><th>Produit</th><th>Type</th><th>Quantité</th><th>Solde</th><th>Note</th></tr></thead><tbody>${movements.slice(0,100).map(m=>{const x=items.find(i=>i.id===m.stockItemId);return`<tr><td>${localDate(m.date)}</td><td>${escapeHtml(x?.name||'Produit supprimé')}</td><td>${escapeHtml(m.type||'')}</td><td>${m.delta>=0?'+':''}${formatNumber(m.delta??m.quantity)} ${escapeHtml(x?.unit||'')}</td><td>${formatNumber(m.balanceAfter)} ${escapeHtml(x?.unit||'')}</td><td>${escapeHtml(m.note||'')}</td></tr>`}).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}


export function traceabilityReportHtml(state,campaign=campaignFor()){
 const rows=traceabilityRows(state,{campaign}),summary=traceabilitySummary(state,{campaign});
 return shell(`Traçabilité ${campaign}`,`<h1>Registre de traçabilité</h1><p class="muted">${escapeHtml(state.exploitation?.nom||'Parcelles')} · campagne ${escapeHtml(campaign)} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${summary.total}</strong><br>interventions</div><div class="kpi"><strong>${summary.withProduct}</strong><br>avec produit</div><div class="kpi"><strong>${summary.withOperator}</strong><br>avec opérateur</div><div class="kpi"><strong>${summary.withAttachment}</strong><br>avec pièce jointe</div></div><table><thead><tr><th>Date</th><th>Parcelle</th><th>Travail</th><th>Produit / dose</th><th>Opérateur</th><th>Matériel</th><th>Statut</th><th>Pièces</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${localDate(r.date)}</td><td>${escapeHtml(r.parcel||'—')}</td><td>${escapeHtml(r.type||'—')}</td><td>${escapeHtml(r.product||'—')}${r.dose!==null&&r.dose!==undefined&&r.dose!==''?` · ${escapeHtml(String(r.dose))} ${escapeHtml(r.unit||'')}`:''}</td><td>${escapeHtml(r.operator||'—')}</td><td>${escapeHtml(r.equipment||'—')}</td><td>${escapeHtml(r.status||'—')}</td><td>${r.documents} doc. · ${r.photos} photo(s)</td></tr>`).join('')}</tbody></table><p class="muted">Ce registre reprend les informations effectivement saisies dans Parcelles. Il facilite la traçabilité interne mais ne certifie pas à lui seul la conformité à une obligation réglementaire particulière.</p><button id="print">Imprimer / PDF</button>`);
}

export function documentsReportHtml(state){
 const docs=filterDocuments(state,{}),summary=documentSummary(state);
 return shell('Registre documentaire',`<h1>Registre documentaire</h1><p class="muted">${escapeHtml(state.exploitation?.nom||'Parcelles')} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${summary.documents}</strong><br>documents</div><div class="kpi"><strong>${summary.photos}</strong><br>photos</div><div class="kpi"><strong>${summary.unlinked}</strong><br>non rattachés</div><div class="kpi"><strong>${formatNumber(summary.bytes/1024/1024)} Mo</strong><br>fichiers indexés</div></div><table><thead><tr><th>Date</th><th>Catégorie</th><th>Document</th><th>Contexte</th><th>Tags</th><th>Taille</th></tr></thead><tbody>${docs.map(d=>`<tr><td>${localDate(d.documentDate||d.createdAt)}</td><td>${escapeHtml(d.category||'Autre')}</td><td>${escapeHtml(d.name||'Document')}</td><td>${escapeHtml(documentContextText(state,d))}</td><td>${escapeHtml((d.tags||[]).join(', '))}</td><td>${formatNumber((d.size||0)/1024)} Ko</td></tr>`).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}
