import {escapeHtml, formatEuro, formatNumber, localDate, toNumber, campaignFor} from './utils.js';
function shell(title,body){return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(title)}</title><style>body{font-family:system-ui,-apple-system,sans-serif;margin:32px;color:#13251c}h1,h2{color:#155c3a}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.kpis{display:flex;gap:20px;flex-wrap:wrap}.kpi{padding:14px 18px;border:1px solid #ddd;border-radius:12px}.muted{color:#667}@media print{button{display:none}body{margin:12mm}}</style></head><body>${body}<script>window.addEventListener('load',()=>document.getElementById('print')?.addEventListener('click',()=>print()))<\/script></body></html>`}
export function farmReportHtml(state){
 const active=t=>(state[t]||[]).filter(x=>!x.deletedAt);const parcels=active('parcelles').filter(p=>(p.ownershipType||'own')==='own'),works=active('interventions');const area=parcels.reduce((s,p)=>s+toNumber(p.surfaceHa),0),campaign=campaignFor();const cw=works.filter(w=>(w.campaignId||campaignFor(w.date))===campaign),cost=cw.reduce((s,w)=>s+toNumber(w.cost),0);const cultures={};parcels.forEach(p=>cultures[p.culture||'Sans culture']=(cultures[p.culture||'Sans culture']||0)+toNumber(p.surfaceHa));
 return shell(`Rapport ${state.exploitation?.nom||'Parcelles'}`,`<h1>${escapeHtml(state.exploitation?.nom||'Parcelles')}</h1><p class="muted">Campagne ${escapeHtml(campaign)} · généré le ${localDate(Date.now())}</p><div class="kpis"><div class="kpi"><strong>${parcels.length}</strong><br>parcelles</div><div class="kpi"><strong>${formatNumber(area)} ha</strong><br>surface</div><div class="kpi"><strong>${cw.length}</strong><br>travaux</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coûts saisis</div></div><h2>Assolement</h2><table><thead><tr><th>Culture</th><th>Surface</th><th>%</th></tr></thead><tbody>${Object.entries(cultures).sort((a,b)=>b[1]-a[1]).map(([c,a])=>`<tr><td>${escapeHtml(c)}</td><td>${formatNumber(a)} ha</td><td>${area?formatNumber(a/area*100):0} %</td></tr>`).join('')}</tbody></table><h2>Travaux de campagne</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Parcelle</th><th>Coût</th></tr></thead><tbody>${cw.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(w=>{const p=parcels.find(p=>p.id===w.parcelId)||(state.parcelles||[]).find(p=>p.id===w.parcelId);return`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(p?.nom||'—')}</td><td>${formatEuro(w.cost)}</td></tr>`}).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}
export function parcelReportHtml(state,parcelId){const p=(state.parcelles||[]).find(x=>x.id===parcelId);if(!p)return'';const works=(state.interventions||[]).filter(w=>!w.deletedAt&&w.parcelId===parcelId).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return shell(`Parcelle ${p.nom}`,`<h1>${escapeHtml(p.nom)}</h1><p>${escapeHtml(p.culture||'Culture non renseignée')} · ${formatNumber(p.surfaceHa)} ha · ${escapeHtml(p.commune||'')}</p>${p.notes?`<p><strong>Note :</strong> ${escapeHtml(p.notes)}</p>`:''}<h2>Historique</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Produit</th><th>Coût</th><th>Note</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(w.product||'')}</td><td>${formatEuro(w.cost)}</td><td>${escapeHtml(w.note||'')}</td></tr>`).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`)}
export function openPrintableReport(html){const blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),win=window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return Boolean(win);}

export function clientReportHtml(state,clientId){
 const client=(state.clients||[]).find(x=>x.id===clientId&&!x.deletedAt);if(!client)return'';
 const parcels=(state.parcelles||[]).filter(p=>!p.deletedAt&&p.clientId===clientId),ids=new Set(parcels.map(p=>p.id));
 const works=(state.interventions||[]).filter(w=>!w.deletedAt&&ids.has(w.parcelId)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const area=parcels.reduce((s,p)=>s+toNumber(p.surfaceHa),0),cost=works.reduce((s,w)=>s+toNumber(w.cost),0);
 return shell(`Client ${client.name}`,`<h1>${escapeHtml(client.name||'Client')}</h1><p class="muted">${escapeHtml(client.contact||client.phone||client.email||'')}</p><div class="kpis"><div class="kpi"><strong>${parcels.length}</strong><br>parcelles</div><div class="kpi"><strong>${formatNumber(area)} ha</strong><br>surface</div><div class="kpi"><strong>${works.length}</strong><br>travaux</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coûts saisis</div></div><h2>Parcelles</h2><table><thead><tr><th>Parcelle</th><th>Culture</th><th>Surface</th><th>Commune</th></tr></thead><tbody>${parcels.map(p=>`<tr><td>${escapeHtml(p.nom)}</td><td>${escapeHtml(p.culture||'')}</td><td>${formatNumber(p.surfaceHa)} ha</td><td>${escapeHtml(p.commune||'')}</td></tr>`).join('')}</tbody></table><h2>Travaux</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Parcelle</th><th>Coût</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date||w.plannedDate)}</td><td>${escapeHtml(w.type||'')}</td><td>${escapeHtml(parcels.find(p=>p.id===w.parcelId)?.nom||'')}</td><td>${formatEuro(w.cost)}</td></tr>`).join('')}</tbody></table>${client.note?`<h2>Note</h2><p>${escapeHtml(client.note)}</p>`:''}<button id="print">Imprimer / PDF</button>`);
}

export function equipmentReportHtml(state,equipmentId){
 const m=(state.materiels||[]).find(x=>x.id===equipmentId&&!x.deletedAt);if(!m)return'';
 const works=(state.interventions||[]).filter(w=>!w.deletedAt&&(w.equipmentId===equipmentId||w.machineId===equipmentId)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const records=(state.maintenanceRecords||[]).filter(r=>!r.deletedAt&&r.equipmentId===equipmentId).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const hours=works.reduce((s,w)=>s+toNumber(w.durationHours),0),cost=works.reduce((s,w)=>s+toNumber(w.machineCost),0),maint=records.reduce((s,r)=>s+toNumber(r.cost),0);
 return shell(`Matériel ${m.nom}`,`<h1>${escapeHtml(m.nom||'Matériel')}</h1><p class="muted">Compteur ${formatNumber(m.currentMeter)} h · prochain entretien ${formatNumber(m.maintenanceDue)} h</p><div class="kpis"><div class="kpi"><strong>${works.length}</strong><br>travaux</div><div class="kpi"><strong>${formatNumber(hours)} h</strong><br>durée saisie</div><div class="kpi"><strong>${formatEuro(cost)}</strong><br>coût machine</div><div class="kpi"><strong>${formatEuro(maint)}</strong><br>entretiens</div></div><h2>Entretiens</h2><table><thead><tr><th>Date</th><th>Compteur</th><th>Opération</th><th>Coût</th></tr></thead><tbody>${records.map(r=>`<tr><td>${localDate(r.date)}</td><td>${formatNumber(r.meter)} h</td><td>${escapeHtml(r.type||r.note||'')}</td><td>${formatEuro(r.cost)}</td></tr>`).join('')}</tbody></table><h2>Utilisation</h2><table><thead><tr><th>Date</th><th>Travail</th><th>Durée</th><th>Coût machine</th></tr></thead><tbody>${works.map(w=>`<tr><td>${localDate(w.date)}</td><td>${escapeHtml(w.type||'')}</td><td>${formatNumber(w.durationHours)} h</td><td>${formatEuro(w.machineCost)}</td></tr>`).join('')}</tbody></table><button id="print">Imprimer / PDF</button>`);
}
