import {YieldRepository,readYieldFiles,suggestMapping,YIELD_FIELDS,DEFAULT_RULES,analyzeYield,displayYieldCells,YIELD_CLASSES,yieldClass,numeric} from './yield.js';
import {escapeHtml as e,downloadBlob} from './utils.js';
const num=v=>v===null?'Non disponible':v.toLocaleString('fr-FR',{maximumFractionDigits:2});
const btn=(action,label,attrs='')=>`<button type="button" class="button secondary" data-yield="${action}" ${attrs}>${label}</button>`;
export function createYieldUI({store,map,modal,closeModal,openParcel,showMap}){
  const repo=new YieldRepository(store);let current=null,sequence=0;
  const parcel=id=>store.snapshot().parcelles.find(p=>p.id===id&&!p.deletedAt);
  function cancel(){sequence++;current=null;}
  function mount(p){cancel();current={p,root:document.querySelector('#yield-panel'),scope:store.workspaceContext().key};render();}
  function render(message=''){
    if(!current?.root.isConnected)return;const{root,p}=current,docs=repo.list(p.id),live=docs.filter(d=>!d.deletedAt),deleted=docs.filter(d=>d.deletedAt);
    root.innerHTML=`<section class="panel"><h2>Rendement</h2><p>Importez les mesures de récolte de cette parcelle. Le fichier brut reste intact.</p>${btn('import','Importer CSV / SHP')}<p class="form-note">CSV en coordonnées WGS84 ou SHP de points avec .dbf et .prj. Maximum 20 000 points / 8 Mo. Données disponibles hors connexion après import ou synchronisation des pièces jointes.</p><p role="status" id="yield-status">${e(message)}</p>${live.map(d=>`<article class="yield-import"><strong>${e(d.name)}</strong><small>${d.yieldMap.pointCount} points bruts · import du ${new Date(d.yieldMap.importedAt).toLocaleDateString('fr-FR')}</small><div class="satellite-actions">${btn('open','Consulter',`data-id="${e(d.id)}"`)}${btn('raw','Télécharger le brut',`data-id="${e(d.id)}"`)}${btn('delete','Mettre à la corbeille',`data-id="${e(d.id)}"`)}</div></article>`).join('')||'<p>Aucune carte de rendement importée.</p>'}${deleted.length?`<details><summary>Corbeille (${deleted.length})</summary>${deleted.map(d=>`<p>${e(d.name)} ${btn('restore','Restaurer',`data-id="${e(d.id)}"`)}</p>`).join('')}</details>`:''}<div id="yield-result"></div></section>`;
  }
  function statsHtml(result){const s=result.stats;return`<p><strong>${result.total} points importés · ${result.points.length} utilisés · ${result.excluded.length} ignorés</strong></p><div class="detail-grid">${[['Moyenne',s.mean,' t/ha'],['Minimum',s.min,' t/ha'],['Maximum',s.max,' t/ha'],['Hétérogénéité (CV)',s.cv,' %'],['Humidité moyenne',s.humidity,' %']].map(([label,value,unit])=>`<div class="metric-card"><small>${label}</small><strong>${num(value)}${value!==null?unit:''}</strong></div>`).join('')}</div><p class="form-note">Moyenne des points retenus, non pondérée par la surface. Humidité : ${s.humidityCount} mesures valides. Aucune correction à une humidité de référence. Surface couverte : non calculable avec des points seuls.</p><details><summary>Mesures retenues (50 premières)</summary>${result.points.slice(0,50).map(p=>`<p>Point ${p.index} · ${num(p.yield)} t/ha · ${e(YIELD_CLASSES[yieldClass(p.yield,s.mean)][0])}<br><small>${e(p.date)} ${e(p.time)} ${e(p.machine)} ${e(p.crop)}</small></p>`).join('')}</details><details><summary>Voir les exclusions (${result.excluded.length})</summary><p>Numéro du point source, sans compter l’en-tête CSV. Les données brutes sont conservées.</p>${result.excluded.slice(0,50).map(p=>`<p>Point ${p.index} : ${e(p.reasons.join(' · '))}</p>`).join('')}${result.excluded.length>50?'<p>50 premières exclusions. Exportez la liste pour tout consulter.</p>':''}</details>`;}
  async function consult(doc){const ctx=current,ticket=++sequence;render('Lecture du fichier brut…');const source=await repo.source(doc);if(ticket!==sequence||!ctx?.root.isConnected||ctx.scope!==store.workspaceContext().key)return;const result=analyzeYield(source,doc.yieldMap,ctx.p);current.doc=doc;current.source=source;current.result=result;render();document.querySelector('#yield-result').innerHTML=`<h3>${e(doc.name)}</h3>${statsHtml(result)}<div class="satellite-actions">${btn('map','Afficher sur la carte',result.points.length?'':'disabled')}${btn('edit','Réglages / recalculer')}${btn('exclusions','Exporter les exclusions')}</div>`;}
  function importer(source=null,files=null,doc=null,selectedId=doc?.parcelId||current?.p.id){const ctx=current;if(!ctx)return;const parcels=store.snapshot().parcelles.filter(p=>!p.deletedAt),config=doc?.yieldMap||{mapping:source?suggestMapping(source.headers):{},rules:{...DEFAULT_RULES},unit:'t/ha'};
    modal(doc?'Recalculer le rendement':'Importer une carte de rendement','Aucun enregistrement avant validation.',`<form id="yield-form" class="form-grid"><label class="span-2">Parcelle<select name="parcelId">${parcels.map(p=>`<option value="${e(p.id)}" ${p.id===selectedId?'selected':''}>${e(p.nom)}</option>`).join('')}</select></label>${!source?'<label class="span-2">Fichier CSV ou jeu SHP<input id="yield-files" type="file" multiple accept=".csv,.shp,.shx,.dbf,.prj,.cpg"></label>':`<p class="span-2">${source.rows.length} points · ${e(source.format.toUpperCase())}. Vérifiez les colonnes et l’unité du fichier.</p>${Object.entries(YIELD_FIELDS).filter(([k])=>source.format==='csv'||!['latitude','longitude'].includes(k)).map(([k,label])=>`<label>${e(label)}<select name="mapping-${k}"><option value="">Non renseigné</option>${source.headers.map(h=>`<option value="${e(h)}" ${config.mapping[k]===h?'selected':''}>${e(h)}</option>`).join('')}</select></label>`).join('')}<label>Unité source<select name="unit">${['t/ha','kg/ha','q/ha'].map(v=>`<option ${config.unit===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Rendement minimum (t/ha)<input name="minYield" type="number" step="any" value="${e(config.rules.minYield)}"></label><label>Rendement maximum (t/ha)<input name="maxYield" type="number" step="any" value="${e(config.rules.maxYield)}"></label><label>Vitesse maximale (km/h)<input name="maxSpeed" type="number" step="any" value="${e(config.rules.maxSpeed)}"></label><label class="span-2"><input name="spikes" type="checkbox" ${config.rules.spikes?'checked':''}> Exclure les pics extrêmes (au moins 8 points, seuil robuste basé sur la médiane)</label><p class="form-note span-2">Adaptez les seuils à la culture et aux unités de la machine. Les points hors contour, coordonnées invalides et doublons exacts sont exclus. Aucune correction des valeurs brutes.</p>`}<p id="yield-import-status" class="span-2" role="status"></p><div id="yield-preview" class="span-2"></div></form>`,`<button class="button secondary" data-action="close-modal">Annuler</button><button class="button primary" id="yield-preview-button">${source?'Calculer l’aperçu':'Lire le fichier'}</button>${source?'<button class="button primary" id="yield-save" disabled>Valider l’import</button>':''}`,'large');
    const form=document.querySelector('#yield-form'),status=document.querySelector('#yield-import-status'),preview=document.querySelector('#yield-preview-button'),save=document.querySelector('#yield-save');let prepared=null;
    form.oninput=()=>{prepared=null;if(save)save.disabled=true;};
    preview.onclick=async()=>{preview.disabled=true;status.textContent='Lecture et vérification…';try{if(!source){const selected=[...document.querySelector('#yield-files').files],parsed=await readYieldFiles(selected);if(current!==ctx||ctx.scope!==store.workspaceContext().key||!form.isConnected)return;importer(parsed,selected,null,form.elements.parcelId.value);return;}
      const mapping=Object.fromEntries(Object.keys(YIELD_FIELDS).map(k=>[k,form.elements['mapping-'+k]?.value||''])),rules={minYield:numeric(form.elements.minYield.value),maxYield:numeric(form.elements.maxYield.value),maxSpeed:numeric(form.elements.maxSpeed.value),spikes:form.elements.spikes.checked},p=parcel(form.elements.parcelId.value),settings={mapping,rules,unit:form.elements.unit.value},result=analyzeYield(source,settings,p);prepared={p,settings,result};document.querySelector('#yield-preview').innerHTML=statsHtml(result);status.textContent=result.points.length?'Vérifiez l’aperçu puis validez.':'Aucun point utilisable : corrigez le mapping, la parcelle ou les seuils.';save.disabled=!result.points.length;
    }catch(error){status.textContent=error.message;}finally{preview.disabled=false;}};
    if(save)save.onclick=async()=>{if(!prepared)return;const submitted=prepared;save.disabled=true;preview.disabled=true;try{if(ctx.scope!==store.workspaceContext().key)throw Error('Exploitation changée : import annulé.');await repo.save(files,source,submitted.settings,submitted.p,doc);closeModal();openParcel(submitted.p.id,'yield');}catch(error){status.textContent=error.message;save.disabled=false;}finally{preview.disabled=false;}};
  }
  function showYield(){const{result,p,doc}=current;showMap(p.id);map.clearFarmOverlay();map.clearSatelliteOverlay();map.clearYieldOverlay();map.init();if(!map.map)throw Error('Carte Leaflet indisponible.');const L=window.L;if(!map.map.getPane('yieldPane')){const pane=map.map.createPane('yieldPane');pane.style.zIndex='440';pane.style.pointerEvents='none';}const renderer=L.canvas({pane:'yieldPane',padding:.3});map.yieldRenderer=renderer;map.yieldParcelId=p.id;map.yieldOverlay=L.layerGroup().addTo(map.map);const cells=displayYieldCells(result.points);
    for(const cell of cells){const c=yieldClass(cell.yield,result.stats.mean);L.circleMarker([cell.latitude,cell.longitude],{renderer,interactive:false,radius:5,stroke:false,fillColor:YIELD_CLASSES[c][1],fillOpacity:.9}).addTo(map.yieldOverlay);}
    const control=L.control({position:'topleft'});control.onAdd=()=>{const div=L.DomUtil.create('div','satellite-map-label yield-map-label');div.innerHTML=`<strong>Rendement · ${num(result.stats.mean)} t/ha</strong><small>${e(p.nom)} · ${result.points.length} points · import ${new Date(doc.yieldMap.importedAt).toLocaleDateString('fr-FR')}</small><details><summary>Légende et méthode</summary>${YIELD_CLASSES.map(([label,color],i)=>`<div><span style="color:${color}">●</span> ${label} · ${['< 70 %','70–90 %','90–110 %','110–130 %','> 130 %'][i]}</div>`).join('')}<small>Classes relatives à la moyenne de cet import. Mesures regroupées par maille de 10 m, sans extrapolation ni mesure de surface.</small></details><button type="button" class="button secondary">Désactiver</button>`;div.querySelector('button').onclick=()=>map.clearYieldOverlay();L.DomEvent.disableClickPropagation(div);L.DomEvent.disableScrollPropagation(div);return div;};control.addTo(map.map);map.yieldControl=control;map.render(map.lastState);
  }
  document.addEventListener('click',async event=>{const b=event.target.closest('[data-yield]');if(!b)return;const action=b.dataset.yield,doc=b.dataset.id?store.get('documents',b.dataset.id,{includeDeleted:true}):current?.doc;try{if(action==='import')importer();else if(action==='open')await consult(doc);else if(action==='edit')importer(current.source,null,current.doc);else if(action==='map')showYield();else if(action==='raw'){const blob=await store.storage.blobGet(doc.id);if(!blob)throw Error('Fichier brut non disponible sur cet appareil.');downloadBlob(doc.name,blob);}else if(action==='exclusions'){downloadBlob('exclusions-rendement.csv',new Blob(['point;motifs\n'+current.result.excluded.map(p=>`${p.index};${p.reasons.join(' / ')}`).join('\n')],{type:'text/csv;charset=utf-8'}));}else if(action==='delete'){await store.remove('documents',doc.id);map.clearYieldOverlay();render('Import placé dans la corbeille ; le brut est conservé.');}else if(action==='restore'){await store.restore('documents',doc.id);render('Import restauré.');}}catch(error){if(current?.root.isConnected)render(error.message);else modal('Rendement','',`<p>${e(error.message)}</p>`);}});
  store.subscribe((_,event)=>{if(event.entity==='documents'||event.entity==='parcelles'||event.entity==='state'){sequence++;map.clearYieldOverlay();if(current?.scope!==store.workspaceContext().key)cancel();}});
  return{mount,cancel};
}
